---
title: "Progamming Basics"
author: "Jasmine Kobayashi"
date: "2022-08-26"
output: html_document
---

```
Hi
```


*Italic*
**Bold**

# Header 1
## Header 2

$A = \pi \times r^{2}$

```{r}
# Code chunks

norm <- rnorm(100,mean = 0, sd=1)   #sd = standard deviation
norm  #normalized distribution of 100 counts with mean =0 and std =1

```

We are going to introduce what a `dataframe` is using R script

```{r, echo=FALSE}
# data frame

A <- c("a","a","b","b")
B <- c(5, 10, 15, 20)
dataframe <- data.frame(A,B)
print(dataframe)

```



`if` and `else` statements in R (aka Conditional Expressions)
```{r}

a <- 5

if(a != 0){
  
  print(1/a)
  
} else{
    print("No reciprocal for 0.")
  }

```

```{r}

library(dslabs)
data(murders)

murder_rate <- murders$total / murders$population*100000
murder_rate

```

Here is a very simple example that tells us which state, if any, have a murder rate lower than 0.5 per 100,000. The `if` statement protects us from the case in which no state satisfies the condition.

```{r}

ind <- which.min(murder_rate)

if (murder_rate[ind] < 0.5){
  
  print(murders$state[ind])
  
} else{
  print("No state has murder rate that low")
}

```

# Define Functions