---
layout: page
title: "CUB-ML Support Vector Machines"
permalink: /CUB-ML/SVM
---
## [CU Boulder: Machine Learning](../CUB-ML.qmd) - 
Most (if not all) code made availabe through her own [website](https://gatesboltonanalytics.com/)

- Reference: Professor Ami Gates, Dept. Applied Math, Data Science, University of Colorado
- All pages of raw-code = unedited code as obtained from Dr. Gates' website
- All markdown versions = versions of Dr. Gates' code cleaned up into a notebook or markdown of somesort (Jupyter or Quarto) edited by me (Jasmine) to show code output, etc.

---

### in R
- N/A (nothing provided, last I checked (April 2023))

### Python

- Single code example (Markdown, [Raw](../DecisionTrees/Raw/Python-DecisionTrees-Raw.qmd)): This code includes Decision Trees, Random Forest, Support Vector Machines, a lot of vis, and several other examples. 
    - [Part 1 - Markdown](../DecisionTrees/Markdown/Python-DecisionTrees.qmd#svm): Text mining example
    - [Part 2 - Markdown](../DecisionTrees/Markdown/Python-DecisionTrees-pt2.qmd#svm): Mixed/Numeric Record data example
