---
layout: page
title: "STAT 5010: Statistical Methods & Applications II"
permalink: /StatII
---

[Fall 2023] ***Stat Methods & App. II*** with Dr. Osita Onyejekwe (Dr. O) at [CU Boulder](../../CUB.qmd)

# Subpages

- [Lecture codes](class_code.qmd)
- [Homeworks](homeworks.qmd)

# Unit 0: R, R-Markdown, Linear Algebra
## Topics:

- Intro to Tidyverse
- Linear Algebra Preliminaries
- Explanation vs. Prediction

## Resources
(No lecture code)

**[Assignments](homeworks.qmd#unit-0-r-r-markdown-linear-algebra):**

- Intro to R Markdown
- Intro to Tidyverse

# Unit 1: Regression Basics
## Topics

- Matrix Representation of the Linear Regression Model
- Justifying Least Squares
- Sums of Squares (TSS, RSS, ESS)

## Resources
**[Lecture material](class_code.qmd#unit-1-regression-basics):**

- Regression Modeling in R - Part 1
- Regression Modeling in R - Part 2


**[Assignment](homeworks.qmd#unit-1-regression-basics):**

- HW1

# Unit 2: Regression Inference, Prediction, and Explanation
## Topics

- Motivating statistical inference in the linear regression context
- Motivating the F-test

## Resources
**[Lecture material](class_code.qmd#unit-2-regression-inference-prediction-and-explanation):**

- T-tests in R
- F-test and T-test
