<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Preprocessing Case Study - Boulder Climate</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="BoulderClimateCaseStudy_files/libs/clipboard/clipboard.min.js"></script>
<script src="BoulderClimateCaseStudy_files/libs/quarto-html/quarto.js"></script>
<script src="BoulderClimateCaseStudy_files/libs/quarto-html/popper.min.js"></script>
<script src="BoulderClimateCaseStudy_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="BoulderClimateCaseStudy_files/libs/quarto-html/anchor.min.js"></script>
<link href="BoulderClimateCaseStudy_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="BoulderClimateCaseStudy_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="BoulderClimateCaseStudy_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="BoulderClimateCaseStudy_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="BoulderClimateCaseStudy_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#data-preprocessing-case-study---boulder-climate" id="toc-data-preprocessing-case-study---boulder-climate" class="nav-link active" data-scroll-target="#data-preprocessing-case-study---boulder-climate">Data Preprocessing Case Study - Boulder Climate</a></li>
  <li><a href="#import-the-data" id="toc-import-the-data" class="nav-link" data-scroll-target="#import-the-data">Import the data</a></li>
  <li><a href="#data-manipulation" id="toc-data-manipulation" class="nav-link" data-scroll-target="#data-manipulation">Data Manipulation</a>
  <ul class="collapse">
  <li><a href="#convert-yearmonthday-to-int" id="toc-convert-yearmonthday-to-int" class="nav-link" data-scroll-target="#convert-yearmonthday-to-int">Convert year/month/day to int</a></li>
  <li><a href="#parse-date" id="toc-parse-date" class="nav-link" data-scroll-target="#parse-date">Parse date</a>
  <ul class="collapse">
  <li><a href="#parse-date-failed." id="toc-parse-date-failed." class="nav-link" data-scroll-target="#parse-date-failed.">Parse date failed.</a></li>
  <li><a href="#save-the-modification" id="toc-save-the-modification" class="nav-link" data-scroll-target="#save-the-modification">Save the modification</a></li>
  </ul></li>
  <li><a href="#missing-values" id="toc-missing-values" class="nav-link" data-scroll-target="#missing-values">Missing values</a>
  <ul class="collapse">
  <li><a href="#find-missing-values" id="toc-find-missing-values" class="nav-link" data-scroll-target="#find-missing-values">Find missing values</a></li>
  <li><a href="#drop-is-simple" id="toc-drop-is-simple" class="nav-link" data-scroll-target="#drop-is-simple">Drop is simple</a></li>
  <li><a href="#filling-takes-more-effort" id="toc-filling-takes-more-effort" class="nav-link" data-scroll-target="#filling-takes-more-effort">Filling takes more effort</a></li>
  <li><a href="#extra-regression" id="toc-extra-regression" class="nav-link" data-scroll-target="#extra-regression">Extra: Regression</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#data-understanding" id="toc-data-understanding" class="nav-link" data-scroll-target="#data-understanding">Data understanding</a>
  <ul class="collapse">
  <li><a href="#attribute-relations" id="toc-attribute-relations" class="nav-link" data-scroll-target="#attribute-relations">Attribute relations</a></li>
  <li><a href="#distribution-plots" id="toc-distribution-plots" class="nav-link" data-scroll-target="#distribution-plots">Distribution plots</a></li>
  </ul></li>
  <li><a href="#data-preprocessing" id="toc-data-preprocessing" class="nav-link" data-scroll-target="#data-preprocessing">Data preprocessing</a>
  <ul class="collapse">
  <li><a href="#create-a-new-attribute-tavg" id="toc-create-a-new-attribute-tavg" class="nav-link" data-scroll-target="#create-a-new-attribute-tavg">Create a new attribute, tavg</a></li>
  <li><a href="#create-a-new-attribute-weather" id="toc-create-a-new-attribute-weather" class="nav-link" data-scroll-target="#create-a-new-attribute-weather">Create a new attribute, weather</a></li>
  <li><a href="#create-a-new-attribute-season" id="toc-create-a-new-attribute-season" class="nav-link" data-scroll-target="#create-a-new-attribute-season">Create a new attribute, season</a></li>
  <li><a href="#create-a-new-attribute-current" id="toc-create-a-new-attribute-current" class="nav-link" data-scroll-target="#create-a-new-attribute-current">Create a new attribute, current</a></li>
  <li><a href="#normalization" id="toc-normalization" class="nav-link" data-scroll-target="#normalization">Normalization</a></li>
  </ul></li>
  <li><a href="#now-lets-save-the-dataset" id="toc-now-lets-save-the-dataset" class="nav-link" data-scroll-target="#now-lets-save-the-dataset">Now let’s save the dataset</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Data Preprocessing Case Study - Boulder Climate</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="data-preprocessing-case-study---boulder-climate" class="level1">
<h1>Data Preprocessing Case Study - Boulder Climate</h1>
<p>Data Explanation:</p>
<p>Source: https://psl.noaa.gov/boulder/getdata.html</p>
<p>Format: converted from .txt to .csv</p>
<ul>
<li>File contains Boulder daily maximum and minimum temperature, precipitation, snowfall and snow cover data.</li>
<li>year,month, iday, imax_temp, imin_temp, precip, snowfall, snowdepth</li>
<li>Temperatures are in degrees Fahrenheit and snow and precipitation are in inches.</li>
<li>Precipitation is the total liquid equivalent of all forms of precipitation (rain, snow, hail,…).</li>
<li>Missing values are indicated by -998.0.</li>
<li>Trace values (less than 1/10 for snow and 1/100 for rain) are indicated by -999.0.</li>
<li>File starts in 1897 though snow doesn’t start until August 1948.</li>
<li>File is usually updated through the last full month.</li>
</ul>
</section>
<section id="import-the-data" class="level1">
<h1>Import the data</h1>
<div class="cell" data-cell_id="38db989ca9074c369f1f6878e4156cbd" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:13}" data-deepnote_cell_type="code" data-execution_millis="1472" data-execution_start="1675035882764" data-source_hash="24b26b86" data-tags="[]" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>pandas.read_csv()</code> is a function used to read a csv file and convert it into a pandas DataFrame. The function takes several arguments, some of which include:</p>
<ul>
<li><code>header</code>: This argument is used to specify the row number(s) to use as the column headers. By default, the first row of the csv file is used as the column header. You can specify a different row number to use as the header by passing an integer value (e.g.&nbsp;<code>header=3</code>) or you can specify that the csv file has no headers by passing <code>None</code> (e.g.&nbsp;<code>header=None</code>)</li>
<li><code>skiprows</code>: This argument is used to specify the number of rows at the beginning of the file to skip. You can pass an integer value (e.g.&nbsp;<code>skiprows=5</code>) or you can pass a list of row numbers to skip (e.g.&nbsp;<code>skiprows=[1,2,5]</code>)</li>
<li><code>names</code>: This argument is used to specify the column names for the DataFrame. If the csv file has no header or the header is being skipped, you can pass a list of column names to use (e.g.&nbsp;<code>names=['col1', 'col2', 'col3']</code>)</li>
</ul>
<div class="cell" data-cell_id="08749b1824114581a6eb116616475ecf" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:19}" data-deepnote_cell_type="code" data-execution_millis="45" data-execution_start="1675035884283" data-source_hash="11cd56c1" data-tags="[]" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">'/work/boulderdaily.csv'</span>, </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                names <span class="op">=</span> [<span class="st">'year'</span>,<span class="st">'month'</span>, <span class="st">'day'</span>, <span class="st">'high'</span>, <span class="st">'low'</span>, <span class="st">'precip'</span>, <span class="st">'snow'</span>, <span class="st">'snowcover'</span>], </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                parse_dates<span class="op">=</span> {<span class="st">"date"</span> : [<span class="st">'year'</span>, <span class="st">"month"</span>, <span class="st">"day"</span>]}, </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>                keep_date_col<span class="op">=</span><span class="va">True</span>, <span class="co"># this separates 'date' into 3 col 'year','month','day' (if false, single column = 'date)</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>                header <span class="op">=</span> <span class="va">None</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>df.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 46116 entries, 0 to 46115
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   date       46116 non-null  object 
 1   year       46116 non-null  object 
 2   month      46116 non-null  object 
 3   day        46116 non-null  object 
 4   high       46116 non-null  int64  
 5   low        46116 non-null  int64  
 6   precip     46116 non-null  float64
 7   snow       46116 non-null  float64
 8   snowcover  46116 non-null  int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 3.2+ MB</code></pre>
</div>
</div>
<div class="cell" data-cell_id="fc6aab1c8b4142b6a7fef4b65c1944a5" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:25}" data-deepnote_cell_type="code" data-deepnote_table_state="{&quot;filters&quot;:[],&quot;pageIndex&quot;:1,&quot;pageSize&quot;:10,&quot;sortBy&quot;:[]}" data-execution_millis="5" data-execution_start="1675035884328" data-source_hash="c085b6ba" data-tags="[]" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">date</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">month</th>
<th data-quarto-table-cell-role="th">day</th>
<th data-quarto-table-cell-role="th">high</th>
<th data-quarto-table-cell-role="th">low</th>
<th data-quarto-table-cell-role="th">precip</th>
<th data-quarto-table-cell-role="th">snow</th>
<th data-quarto-table-cell-role="th">snowcover</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1897 1 1</td>
<td>1897</td>
<td>1</td>
<td>1</td>
<td>-998</td>
<td>-998</td>
<td>-998.0</td>
<td>-998.0</td>
<td>-998</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1897 1 2</td>
<td>1897</td>
<td>1</td>
<td>2</td>
<td>-998</td>
<td>-998</td>
<td>-998.0</td>
<td>-998.0</td>
<td>-998</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1897 1 3</td>
<td>1897</td>
<td>1</td>
<td>3</td>
<td>-998</td>
<td>-998</td>
<td>-998.0</td>
<td>-998.0</td>
<td>-998</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>1897 1 4</td>
<td>1897</td>
<td>1</td>
<td>4</td>
<td>-998</td>
<td>-998</td>
<td>-998.0</td>
<td>-998.0</td>
<td>-998</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>1897 1 5</td>
<td>1897</td>
<td>1</td>
<td>5</td>
<td>-998</td>
<td>-998</td>
<td>-998.0</td>
<td>-998.0</td>
<td>-998</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="data-manipulation" class="level1">
<h1>Data Manipulation</h1>
<section id="convert-yearmonthday-to-int" class="level2">
<h2 class="anchored" data-anchor-id="convert-yearmonthday-to-int">Convert year/month/day to int</h2>
<p>The <code>astype()</code> function in pandas is used to cast a pandas object to a specified data type. This function can be used to convert one or multiple columns in a DataFrame or Series to a different data type.</p>
<div class="cell" data-cell_id="9bec7d30072f4f35b4f86fc07c806d41" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:37}" data-deepnote_cell_type="code" data-execution_millis="12" data-execution_start="1675035884339" data-source_hash="9dad28bf" data-tags="[]" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'year'</span>] <span class="op">=</span> df[<span class="st">'year'</span>].astype(<span class="st">'int'</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'month'</span>] <span class="op">=</span> df[<span class="st">'month'</span>].astype(<span class="st">'int'</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'day'</span>] <span class="op">=</span> df[<span class="st">'day'</span>].astype(<span class="st">'int'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="parse-date" class="level2">
<h2 class="anchored" data-anchor-id="parse-date">Parse date</h2>
<p>The <code>to_datetime()</code> function in pandas is used to convert an object to a datetime object. It can take several arguments, including:</p>
<ul>
<li><code>arg</code>: The object to be converted. It can be a string, list, array, or series. format: A string representing the format of the input. This is useful when the input is a string and its format is not automatically detected.</li>
<li><code>errors</code>: A string or callable indicating how to handle errors during the conversion. The options include ‘raise’, ‘coerce’, ‘ignore’.</li>
<li><code>utc</code>: A boolean indicating whether to convert the datetime to UTC.</li>
<li><code>dayfirst</code>: A boolean indicating whether the first value of a date is the day or the month.</li>
<li><code>yearfirst</code>: A boolean indicating whether the first value of a date is the year or the month.</li>
<li><code>exact</code>: A boolean indicating whether to require an exact format match. Example : <code>df['date'] = pd.to_datetime(df['date'], format='%d/%m/%Y', errors='coerce')</code></li>
</ul>
<p>This code will convert the <code>'date'</code> column of a DataFrame <code>df</code> to datetime format, assuming that the input is in the format <code>'dd/mm/yyyy'</code>. If there are any errors during the conversion, they will be coerced (replaced with <code>NaT</code>).</p>
<div class="cell" data-cell_id="5b1f6d56a68047498b64fc89c937e281" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:49}" data-deepnote_cell_type="code" data-execution_millis="11" data-execution_start="1675035884360" data-outputid="8242e89d-21d0-49cf-e25d-b48fa22bbe14" data-source_hash="26bfd6b7" data-execution_count="5">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#df['date'] = pd.to_datetime(df['date'])   # this will not work</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>df.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 46116 entries, 0 to 46115
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   date       46116 non-null  object 
 1   year       46116 non-null  int64  
 2   month      46116 non-null  int64  
 3   day        46116 non-null  int64  
 4   high       46116 non-null  int64  
 5   low        46116 non-null  int64  
 6   precip     46116 non-null  float64
 7   snow       46116 non-null  float64
 8   snowcover  46116 non-null  int64  
dtypes: float64(2), int64(6), object(1)
memory usage: 3.2+ MB</code></pre>
</div>
</div>
<section id="parse-date-failed." class="level3">
<h3 class="anchored" data-anchor-id="parse-date-failed.">Parse date failed.</h3>
<p>we find out the reason is there are invalid dates, such as 2021 Feb 29. We need to remove those error before parsing dates.</p>
<section id="you-can-use-the-optional-argument-errors" class="level4">
<h4 class="anchored" data-anchor-id="you-can-use-the-optional-argument-errors">You can use the optional argument <code>errors</code></h4>
<div class="cell" data-cell_id="4639b4ed3b224684bc9c1f6e845cd8a1" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0}" data-deepnote_cell_type="code" data-execution_millis="8" data-execution_start="1675035884407" data-source_hash="b64155d8" data-tags="[]" data-execution_count="6">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>df2 <span class="op">=</span> df</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>df2[<span class="st">'date'</span>] <span class="op">=</span> pd.to_datetime(df2[<span class="st">'date'</span>], errors <span class="op">=</span> <span class="st">'coerce'</span>)  <span class="co"># errors='coerce' will ignore the errors</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>df2.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 46116 entries, 0 to 46115
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype         
---  ------     --------------  -----         
 0   date       46020 non-null  datetime64[ns]
 1   year       46116 non-null  int64         
 2   month      46116 non-null  int64         
 3   day        46116 non-null  int64         
 4   high       46116 non-null  int64         
 5   low        46116 non-null  int64         
 6   precip     46116 non-null  float64       
 7   snow       46116 non-null  float64       
 8   snowcover  46116 non-null  int64         
dtypes: datetime64[ns](1), float64(2), int64(6)
memory usage: 3.2 MB</code></pre>
</div>
</div>
<p>The <code>dropna()</code> function in pandas is used to remove missing values from a DataFrame. The <code>inplace</code> argument is used to specify whether the function should make changes to the original DataFrame or return a new DataFrame with the changes. If <code>inplace=True</code>, the function will make changes to the original DataFrame and nothing will be returned. If <code>inplace=False</code>, the function will return a new DataFrame with missing values removed. The default value of inplace is <code>False</code></p>
<div class="cell" data-cell_id="5cb37a8d5ff440e9875710d90a50550c" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0}" data-deepnote_cell_type="code" data-execution_millis="2" data-execution_start="1675035884455" data-source_hash="3667064b" data-tags="[]" data-execution_count="7">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>df2.dropna(inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>df2.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
Int64Index: 46020 entries, 0 to 46115
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype         
---  ------     --------------  -----         
 0   date       46020 non-null  datetime64[ns]
 1   year       46020 non-null  int64         
 2   month      46020 non-null  int64         
 3   day        46020 non-null  int64         
 4   high       46020 non-null  int64         
 5   low        46020 non-null  int64         
 6   precip     46020 non-null  float64       
 7   snow       46020 non-null  float64       
 8   snowcover  46020 non-null  int64         
dtypes: datetime64[ns](1), float64(2), int64(6)
memory usage: 3.5 MB</code></pre>
</div>
</div>
</section>
<section id="you-can-also-find-and-drop-the-invalid-dates" class="level4">
<h4 class="anchored" data-anchor-id="you-can-also-find-and-drop-the-invalid-dates">You can also find and drop the invalid dates</h4>
<p>Here you can always save the modified df as a temporary one, df3, for example. If you are confident, you can have <code>inplace = True</code> as the argument to modify the df directly.</p>
<p>The <code>drop()</code> function in pandas is used to drop specified labels from rows or columns of a DataFrame. It takes several arguments:</p>
<ul>
<li><code>labels</code>: This is the single or list of labels to be removed.</li>
<li><code>axis</code>: This specifies whether to drop rows (<code>0</code> or <code>'index'</code>) or columns (<code>1</code> or <code>'columns'</code>). The default value is <code>0</code>.</li>
<li><code>index</code>: This is the single or list of index to be removed.</li>
<li><code>columns</code>: This is the single or list of columns to be removed.</li>
</ul>
<div class="cell" data-cell_id="f520aec5810b4a63baed82e40ff01e73" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:67}" data-deepnote_cell_type="code" data-execution_millis="36" data-execution_start="1675035884455" data-source_hash="a510e849" data-tags="[]" data-execution_count="8">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>df3 <span class="op">=</span> df.drop(df[(df[<span class="st">'month'</span>] <span class="op">==</span> <span class="dv">2</span>) <span class="op">&amp;</span> (df[<span class="st">'day'</span>] <span class="op">==</span> <span class="dv">29</span>)].index) <span class="co"># can work to do the same thing as above</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                                                                <span class="co"># but not the best...</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>df3.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
Int64Index: 45990 entries, 0 to 46115
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype         
---  ------     --------------  -----         
 0   date       45990 non-null  datetime64[ns]
 1   year       45990 non-null  int64         
 2   month      45990 non-null  int64         
 3   day        45990 non-null  int64         
 4   high       45990 non-null  int64         
 5   low        45990 non-null  int64         
 6   precip     45990 non-null  float64       
 7   snow       45990 non-null  float64       
 8   snowcover  45990 non-null  int64         
dtypes: datetime64[ns](1), float64(2), int64(6)
memory usage: 3.5 MB</code></pre>
</div>
</div>
<div class="cell" data-cell_id="c3d32e13f0914fe2a37ed9b071d169a2" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:73}" data-deepnote_cell_type="code" data-execution_millis="5" data-execution_start="1675035884486" data-source_hash="f33ce007" data-tags="[]" data-execution_count="9">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>df3[<span class="st">'date'</span>] <span class="op">=</span> pd.to_datetime(df3[<span class="st">'date'</span>])</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>df3.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
Int64Index: 45990 entries, 0 to 46115
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype         
---  ------     --------------  -----         
 0   date       45990 non-null  datetime64[ns]
 1   year       45990 non-null  int64         
 2   month      45990 non-null  int64         
 3   day        45990 non-null  int64         
 4   high       45990 non-null  int64         
 5   low        45990 non-null  int64         
 6   precip     45990 non-null  float64       
 7   snow       45990 non-null  float64       
 8   snowcover  45990 non-null  int64         
dtypes: datetime64[ns](1), float64(2), int64(6)
memory usage: 3.5 MB</code></pre>
</div>
</div>
</section>
</section>
<section id="save-the-modification" class="level3">
<h3 class="anchored" data-anchor-id="save-the-modification">Save the modification</h3>
<p>Now it looks good. You can save the modified df and replace the original one.</p>
<div class="cell" data-cell_id="a82136faab7d4a0b83f87aada86d8d76" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:85}" data-deepnote_cell_type="code" data-execution_start="1675035884486" data-source_hash="f25a2d1f" data-tags="[]" data-execution_count="10">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-cell_id="30ce82c327ef4d0893cfbf0c384bd48c" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:91}" data-deepnote_cell_type="code" data-execution_millis="48" data-execution_start="1675035884487" data-outputid="3777c951-24aa-43f7-cece-6d83a1039707" data-source_hash="f88152d9" data-execution_count="11">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>df.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">month</th>
<th data-quarto-table-cell-role="th">day</th>
<th data-quarto-table-cell-role="th">high</th>
<th data-quarto-table-cell-role="th">low</th>
<th data-quarto-table-cell-role="th">precip</th>
<th data-quarto-table-cell-role="th">snow</th>
<th data-quarto-table-cell-role="th">snowcover</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>46020.000000</td>
<td>46020.000000</td>
<td>46020.000000</td>
<td>46020.000000</td>
<td>46020.000000</td>
<td>46020.000000</td>
<td>46020.000000</td>
<td>46020.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>1959.501630</td>
<td>6.523077</td>
<td>15.729205</td>
<td>48.228879</td>
<td>21.091569</td>
<td>-104.650636</td>
<td>-450.247625</td>
<td>-472.979596</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>36.371259</td>
<td>3.448700</td>
<td>8.800005</td>
<td>131.855477</td>
<td>133.456999</td>
<td>305.992189</td>
<td>496.780334</td>
<td>498.659503</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>1897.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>-998.000000</td>
<td>-999.000000</td>
<td>-999.000000</td>
<td>-999.000000</td>
<td>-999.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>1928.000000</td>
<td>4.000000</td>
<td>8.000000</td>
<td>51.000000</td>
<td>26.000000</td>
<td>0.000000</td>
<td>-998.000000</td>
<td>-998.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>1960.000000</td>
<td>7.000000</td>
<td>16.000000</td>
<td>65.000000</td>
<td>38.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>1991.000000</td>
<td>10.000000</td>
<td>23.000000</td>
<td>80.000000</td>
<td>52.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>2022.000000</td>
<td>12.000000</td>
<td>31.000000</td>
<td>104.000000</td>
<td>82.000000</td>
<td>9.080000</td>
<td>22.100000</td>
<td>27.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
</section>
<section id="missing-values" class="level2">
<h2 class="anchored" data-anchor-id="missing-values">Missing values</h2>
<p>In the original dataset, missing values are marked as -998 and -999. We should take care of that coding.</p>
<section id="find-missing-values" class="level3">
<h3 class="anchored" data-anchor-id="find-missing-values">Find missing values</h3>
<div class="cell" data-cell_id="695039a5eafb4820ba6568006a9c88aa" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:103}" data-deepnote_cell_type="code" data-execution_start="1675035884579" data-source_hash="78388237" data-tags="[]" data-execution_count="12">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> findNone(x):</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> x <span class="op">&lt;</span> <span class="op">-</span><span class="dv">200</span>:</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">None</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-cell_id="61acddd0229240c4a2bac4f6ce39dbaf" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:109}" data-deepnote_cell_type="code" data-execution_millis="48" data-execution_start="1675035884579" data-source_hash="7df8b1d2" data-tags="[]" data-execution_count="13">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>cols <span class="op">=</span> df.columns[<span class="dv">4</span>:]</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> cols:</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    df[col] <span class="op">=</span> df[col].<span class="bu">apply</span>(findNone)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-cell_id="835e81a867e747d8a48b937bbbf210b4" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:115}" data-deepnote_cell_type="code" data-execution_millis="3" data-execution_start="1675035884627" data-source_hash="de1e323c" data-tags="[]" data-execution_count="14">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>df.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
Int64Index: 46020 entries, 0 to 46115
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype         
---  ------     --------------  -----         
 0   date       46020 non-null  datetime64[ns]
 1   year       46020 non-null  int64         
 2   month      46020 non-null  int64         
 3   day        46020 non-null  int64         
 4   high       45314 non-null  float64       
 5   low        45255 non-null  float64       
 6   precip     41196 non-null  float64       
 7   snow       25253 non-null  float64       
 8   snowcover  24198 non-null  float64       
dtypes: datetime64[ns](1), float64(5), int64(3)
memory usage: 4.5 MB</code></pre>
</div>
</div>
</section>
<section id="drop-is-simple" class="level3">
<h3 class="anchored" data-anchor-id="drop-is-simple">Drop is simple</h3>
<p>We can drop or fill (with different options) these missing falues.</p>
<div class="cell" data-cell_id="dba7d8b301974d02bbbd9a895dcf0f1d" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:451}" data-deepnote_cell_type="code" data-execution_millis="44" data-execution_start="1675035884628" data-source_hash="9f4193d6" data-tags="[]" data-execution_count="15">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>df_drop <span class="op">=</span> df.dropna()</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>df_drop.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
Int64Index: 20810 entries, 18879 to 46115
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype         
---  ------     --------------  -----         
 0   date       20810 non-null  datetime64[ns]
 1   year       20810 non-null  int64         
 2   month      20810 non-null  int64         
 3   day        20810 non-null  int64         
 4   high       20810 non-null  float64       
 5   low        20810 non-null  float64       
 6   precip     20810 non-null  float64       
 7   snow       20810 non-null  float64       
 8   snowcover  20810 non-null  float64       
dtypes: datetime64[ns](1), float64(5), int64(3)
memory usage: 1.6 MB</code></pre>
</div>
</div>
</section>
<section id="filling-takes-more-effort" class="level3">
<h3 class="anchored" data-anchor-id="filling-takes-more-effort">Filling takes more effort</h3>
<div class="cell" data-cell_id="4f680a30964543308371f172710e62c9" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:457}" data-deepnote_cell_type="code" data-execution_millis="2" data-execution_start="1675035884671" data-source_hash="c11efc0b" data-tags="[]" data-execution_count="16">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>df_filled_with_mean <span class="op">=</span> df.fillna(df.mean())</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>df_filled_with_mean.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
Int64Index: 46020 entries, 0 to 46115
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype         
---  ------     --------------  -----         
 0   date       46020 non-null  datetime64[ns]
 1   year       46020 non-null  int64         
 2   month      46020 non-null  int64         
 3   day        46020 non-null  int64         
 4   high       46020 non-null  float64       
 5   low        46020 non-null  float64       
 6   precip     46020 non-null  float64       
 7   snow       46020 non-null  float64       
 8   snowcover  46020 non-null  float64       
dtypes: datetime64[ns](1), float64(5), int64(3)
memory usage: 4.5 MB
/tmp/ipykernel_1349/1845878698.py:1: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  df_filled_with_mean = df.fillna(df.mean())</code></pre>
</div>
</div>
<div class="cell" data-cell_id="3ea141f1e41b4d9ba95340323ea8ca11" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:463}" data-deepnote_cell_type="code" data-execution_millis="41" data-execution_start="1675035884672" data-source_hash="e546ca18" data-tags="[]" data-execution_count="17">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>df_timeseries <span class="op">=</span> df.sort_values(by<span class="op">=</span>[<span class="st">'year'</span>, <span class="st">'month'</span>, <span class="st">'date'</span>])</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>df_timeseries.head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">date</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">month</th>
<th data-quarto-table-cell-role="th">day</th>
<th data-quarto-table-cell-role="th">high</th>
<th data-quarto-table-cell-role="th">low</th>
<th data-quarto-table-cell-role="th">precip</th>
<th data-quarto-table-cell-role="th">snow</th>
<th data-quarto-table-cell-role="th">snowcover</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1897-01-01</td>
<td>1897</td>
<td>1</td>
<td>1</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1897-01-02</td>
<td>1897</td>
<td>1</td>
<td>2</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1897-01-03</td>
<td>1897</td>
<td>1</td>
<td>3</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>1897-01-04</td>
<td>1897</td>
<td>1</td>
<td>4</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>1897-01-05</td>
<td>1897</td>
<td>1</td>
<td>5</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>1897-01-06</td>
<td>1897</td>
<td>1</td>
<td>6</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>1897-01-07</td>
<td>1897</td>
<td>1</td>
<td>7</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>1897-01-08</td>
<td>1897</td>
<td>1</td>
<td>8</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>1897-01-09</td>
<td>1897</td>
<td>1</td>
<td>9</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>1897-01-10</td>
<td>1897</td>
<td>1</td>
<td>10</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-cell_id="55a7f82249f04eadb4b3b3103f92eaa4" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:469}" data-deepnote_cell_type="code" data-execution_millis="45" data-execution_start="1675035884712" data-source_hash="733fc124" data-tags="[]" data-execution_count="18">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>df_backfill <span class="op">=</span> df_timeseries.fillna(method <span class="op">=</span> <span class="st">'bfill'</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>df_backfill.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">month</th>
<th data-quarto-table-cell-role="th">day</th>
<th data-quarto-table-cell-role="th">high</th>
<th data-quarto-table-cell-role="th">low</th>
<th data-quarto-table-cell-role="th">precip</th>
<th data-quarto-table-cell-role="th">snow</th>
<th data-quarto-table-cell-role="th">snowcover</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>46020.000000</td>
<td>46020.000000</td>
<td>46020.000000</td>
<td>46020.000000</td>
<td>46020.000000</td>
<td>46020.000000</td>
<td>46020.000000</td>
<td>46020.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>1959.501630</td>
<td>6.523077</td>
<td>15.729205</td>
<td>64.581704</td>
<td>38.404715</td>
<td>0.058873</td>
<td>0.153646</td>
<td>0.343220</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>36.371259</td>
<td>3.448700</td>
<td>8.800005</td>
<td>18.316433</td>
<td>16.037665</td>
<td>0.198771</td>
<td>0.936575</td>
<td>1.413121</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>1897.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>-12.000000</td>
<td>-33.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>1928.000000</td>
<td>4.000000</td>
<td>8.000000</td>
<td>51.000000</td>
<td>27.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>1960.000000</td>
<td>7.000000</td>
<td>16.000000</td>
<td>65.000000</td>
<td>39.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>1991.000000</td>
<td>10.000000</td>
<td>23.000000</td>
<td>80.000000</td>
<td>52.000000</td>
<td>0.010000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>2022.000000</td>
<td>12.000000</td>
<td>31.000000</td>
<td>104.000000</td>
<td>82.000000</td>
<td>9.080000</td>
<td>22.100000</td>
<td>27.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-cell_id="3d99e472e2584e20bcdcdc89887a9e57" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:475}" data-deepnote_cell_type="code" data-execution_millis="25" data-execution_start="1675035884802" data-source_hash="10fd7b41" data-tags="[]" data-execution_count="19">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>df_forwardfill <span class="op">=</span> df_timeseries.fillna(method <span class="op">=</span> <span class="st">'ffill'</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>df_forwardfill.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="19">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">month</th>
<th data-quarto-table-cell-role="th">day</th>
<th data-quarto-table-cell-role="th">high</th>
<th data-quarto-table-cell-role="th">low</th>
<th data-quarto-table-cell-role="th">precip</th>
<th data-quarto-table-cell-role="th">snow</th>
<th data-quarto-table-cell-role="th">snowcover</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>46020.000000</td>
<td>46020.000000</td>
<td>46020.000000</td>
<td>45900.000000</td>
<td>45900.000000</td>
<td>45900.000000</td>
<td>27181.000000</td>
<td>27181.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>1959.501630</td>
<td>6.523077</td>
<td>15.729205</td>
<td>64.682244</td>
<td>38.460327</td>
<td>0.056652</td>
<td>0.252412</td>
<td>0.606968</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>36.371259</td>
<td>3.448700</td>
<td>8.800005</td>
<td>18.353563</td>
<td>16.128064</td>
<td>0.193257</td>
<td>1.182312</td>
<td>1.787849</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>1897.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>-12.000000</td>
<td>-33.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>1928.000000</td>
<td>4.000000</td>
<td>8.000000</td>
<td>51.000000</td>
<td>27.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>1960.000000</td>
<td>7.000000</td>
<td>16.000000</td>
<td>66.000000</td>
<td>39.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>1991.000000</td>
<td>10.000000</td>
<td>23.000000</td>
<td>80.000000</td>
<td>52.000000</td>
<td>0.010000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>2022.000000</td>
<td>12.000000</td>
<td>31.000000</td>
<td>104.000000</td>
<td>82.000000</td>
<td>9.080000</td>
<td>22.100000</td>
<td>27.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-cell_id="32f86785d3284ee3a0bd33bbae3d8ac5" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:481}" data-deepnote_cell_type="code" data-execution_millis="30" data-execution_start="1675035884830" data-source_hash="cd6a13bc" data-tags="[]" data-execution_count="20">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>df_day_avg <span class="op">=</span> df[df.columns[<span class="dv">2</span>:]].groupby([<span class="st">'month'</span>, <span class="st">'day'</span>]).mean()</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>df_day_avg.columns <span class="op">=</span> [<span class="st">'high_mean'</span>, <span class="st">'low_mean'</span>, <span class="st">'precip_mean'</span>, <span class="st">'snow_mean'</span>, <span class="st">'snowcover_mean'</span>]</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>df_day_avg</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">high_mean</th>
<th data-quarto-table-cell-role="th">low_mean</th>
<th data-quarto-table-cell-role="th">precip_mean</th>
<th data-quarto-table-cell-role="th">snow_mean</th>
<th data-quarto-table-cell-role="th">snowcover_mean</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">month</th>
<th data-quarto-table-cell-role="th">day</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td rowspan="5" data-quarto-table-cell-role="th" data-valign="top">1</td>
<td data-quarto-table-cell-role="th">1</td>
<td>41.243902</td>
<td>18.747967</td>
<td>0.025478</td>
<td>0.529851</td>
<td>2.152542</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>43.715447</td>
<td>17.861789</td>
<td>0.011441</td>
<td>0.294203</td>
<td>1.968254</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>43.780488</td>
<td>19.634146</td>
<td>0.025424</td>
<td>0.453623</td>
<td>2.351852</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>43.943089</td>
<td>19.918699</td>
<td>0.028509</td>
<td>0.523077</td>
<td>2.322034</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>44.691057</td>
<td>20.146341</td>
<td>0.026991</td>
<td>0.557812</td>
<td>2.410714</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td rowspan="5" data-quarto-table-cell-role="th" data-valign="top">12</td>
<td data-quarto-table-cell-role="th">27</td>
<td>44.640000</td>
<td>20.520000</td>
<td>0.042456</td>
<td>0.728125</td>
<td>2.245614</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">28</td>
<td>46.232000</td>
<td>21.624000</td>
<td>0.019009</td>
<td>0.412308</td>
<td>2.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">29</td>
<td>44.200000</td>
<td>21.120000</td>
<td>0.035726</td>
<td>0.616923</td>
<td>2.203390</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">30</td>
<td>44.640000</td>
<td>20.696000</td>
<td>0.024091</td>
<td>0.340000</td>
<td>2.200000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">31</td>
<td>43.312000</td>
<td>18.832000</td>
<td>0.015929</td>
<td>0.390909</td>
<td>2.118644</td>
</tr>
</tbody>
</table>

<p>366 rows × 5 columns</p>
</div>
</div>
</div>
<div class="cell" data-cell_id="993e784faa84404d9ad1af453354e134" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:487}" data-deepnote_cell_type="code" data-execution_millis="43" data-execution_start="1675035884863" data-source_hash="ec5ce294" data-tags="[]" data-execution_count="21">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>df_day_max <span class="op">=</span> df[df.columns[<span class="dv">2</span>:]].groupby([<span class="st">'month'</span>, <span class="st">'day'</span>]).<span class="bu">max</span>()</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>df_day_max.columns <span class="op">=</span> [<span class="st">'high_max'</span>, <span class="st">'low_max'</span>, <span class="st">'precip_max'</span>, <span class="st">'snow_max'</span>, <span class="st">'snowcover_max'</span>]</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>df_day_max</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">high_max</th>
<th data-quarto-table-cell-role="th">low_max</th>
<th data-quarto-table-cell-role="th">precip_max</th>
<th data-quarto-table-cell-role="th">snow_max</th>
<th data-quarto-table-cell-role="th">snowcover_max</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">month</th>
<th data-quarto-table-cell-role="th">day</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td rowspan="5" data-quarto-table-cell-role="th" data-valign="top">1</td>
<td data-quarto-table-cell-role="th">1</td>
<td>70.0</td>
<td>45.0</td>
<td>0.46</td>
<td>7.5</td>
<td>12.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>70.0</td>
<td>49.0</td>
<td>0.32</td>
<td>6.0</td>
<td>11.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>68.0</td>
<td>44.0</td>
<td>0.59</td>
<td>8.5</td>
<td>12.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>67.0</td>
<td>44.0</td>
<td>0.83</td>
<td>10.7</td>
<td>13.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>69.0</td>
<td>44.0</td>
<td>0.91</td>
<td>11.5</td>
<td>17.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td rowspan="5" data-quarto-table-cell-role="th" data-valign="top">12</td>
<td data-quarto-table-cell-role="th">27</td>
<td>74.0</td>
<td>44.0</td>
<td>0.98</td>
<td>12.6</td>
<td>19.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">28</td>
<td>67.0</td>
<td>47.0</td>
<td>0.44</td>
<td>9.0</td>
<td>16.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">29</td>
<td>69.0</td>
<td>44.0</td>
<td>1.26</td>
<td>12.5</td>
<td>17.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">30</td>
<td>71.0</td>
<td>49.0</td>
<td>0.52</td>
<td>6.2</td>
<td>13.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">31</td>
<td>66.0</td>
<td>48.0</td>
<td>0.32</td>
<td>8.0</td>
<td>13.0</td>
</tr>
</tbody>
</table>

<p>366 rows × 5 columns</p>
</div>
</div>
</div>
<div class="cell" data-cell_id="ad72b458435d4cc29013b26ccb3fc8ce" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:493}" data-deepnote_cell_type="code" data-execution_millis="24" data-execution_start="1675035884909" data-source_hash="6e1bf347" data-tags="[]" data-execution_count="22">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>df_day_min <span class="op">=</span> df[df.columns[<span class="dv">2</span>:]].groupby([<span class="st">'month'</span>, <span class="st">'day'</span>]).<span class="bu">min</span>()</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>df_day_min.columns <span class="op">=</span> [<span class="st">'high_min'</span>, <span class="st">'low_min'</span>, <span class="st">'precip_min'</span>, <span class="st">'snow_min'</span>, <span class="st">'snowcover_min'</span>]</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>df_day_min</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">high_min</th>
<th data-quarto-table-cell-role="th">low_min</th>
<th data-quarto-table-cell-role="th">precip_min</th>
<th data-quarto-table-cell-role="th">snow_min</th>
<th data-quarto-table-cell-role="th">snowcover_min</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">month</th>
<th data-quarto-table-cell-role="th">day</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td rowspan="5" data-quarto-table-cell-role="th" data-valign="top">1</td>
<td data-quarto-table-cell-role="th">1</td>
<td>-3.0</td>
<td>-14.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>4.0</td>
<td>-14.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>4.0</td>
<td>-10.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>8.0</td>
<td>-14.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>8.0</td>
<td>-13.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td rowspan="5" data-quarto-table-cell-role="th" data-valign="top">12</td>
<td data-quarto-table-cell-role="th">27</td>
<td>8.0</td>
<td>-10.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">28</td>
<td>15.0</td>
<td>-8.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">29</td>
<td>11.0</td>
<td>-10.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">30</td>
<td>8.0</td>
<td>-11.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">31</td>
<td>6.0</td>
<td>-18.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
</tr>
</tbody>
</table>

<p>366 rows × 5 columns</p>
</div>
</div>
</div>
<div class="cell" data-cell_id="85d037bf0b1f4ad48d1f4ab62e908390" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:499}" data-deepnote_cell_type="code" data-execution_millis="4" data-execution_start="1675035884975" data-source_hash="a4a788d5" data-tags="[]" data-execution_count="23">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>df_day <span class="op">=</span> pd.merge(df_day_max,df_day_min, on <span class="op">=</span> [<span class="st">'month'</span>, <span class="st">'day'</span>])</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>df_day <span class="op">=</span> pd.merge(df_day,df_day_avg, on <span class="op">=</span> [<span class="st">'month'</span>, <span class="st">'day'</span>])</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>df_day.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">high_max</th>
<th data-quarto-table-cell-role="th">low_max</th>
<th data-quarto-table-cell-role="th">precip_max</th>
<th data-quarto-table-cell-role="th">snow_max</th>
<th data-quarto-table-cell-role="th">snowcover_max</th>
<th data-quarto-table-cell-role="th">high_min</th>
<th data-quarto-table-cell-role="th">low_min</th>
<th data-quarto-table-cell-role="th">precip_min</th>
<th data-quarto-table-cell-role="th">snow_min</th>
<th data-quarto-table-cell-role="th">snowcover_min</th>
<th data-quarto-table-cell-role="th">high_mean</th>
<th data-quarto-table-cell-role="th">low_mean</th>
<th data-quarto-table-cell-role="th">precip_mean</th>
<th data-quarto-table-cell-role="th">snow_mean</th>
<th data-quarto-table-cell-role="th">snowcover_mean</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">month</th>
<th data-quarto-table-cell-role="th">day</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td rowspan="5" data-quarto-table-cell-role="th" data-valign="top">1</td>
<td data-quarto-table-cell-role="th">1</td>
<td>70.0</td>
<td>45.0</td>
<td>0.46</td>
<td>7.5</td>
<td>12.0</td>
<td>-3.0</td>
<td>-14.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>41.243902</td>
<td>18.747967</td>
<td>0.025478</td>
<td>0.529851</td>
<td>2.152542</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>70.0</td>
<td>49.0</td>
<td>0.32</td>
<td>6.0</td>
<td>11.0</td>
<td>4.0</td>
<td>-14.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>43.715447</td>
<td>17.861789</td>
<td>0.011441</td>
<td>0.294203</td>
<td>1.968254</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>68.0</td>
<td>44.0</td>
<td>0.59</td>
<td>8.5</td>
<td>12.0</td>
<td>4.0</td>
<td>-10.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>43.780488</td>
<td>19.634146</td>
<td>0.025424</td>
<td>0.453623</td>
<td>2.351852</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>67.0</td>
<td>44.0</td>
<td>0.83</td>
<td>10.7</td>
<td>13.0</td>
<td>8.0</td>
<td>-14.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>43.943089</td>
<td>19.918699</td>
<td>0.028509</td>
<td>0.523077</td>
<td>2.322034</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>69.0</td>
<td>44.0</td>
<td>0.91</td>
<td>11.5</td>
<td>17.0</td>
<td>8.0</td>
<td>-13.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>44.691057</td>
<td>20.146341</td>
<td>0.026991</td>
<td>0.557812</td>
<td>2.410714</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-cell_id="944dff32ba0e46b2920a782e842fcd99" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:505}" data-deepnote_cell_type="code" data-execution_millis="3" data-execution_start="1675035885043" data-source_hash="d1cdbc38" data-tags="[]" data-execution_count="24">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>df_day.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
MultiIndex: 366 entries, (1, 1) to (12, 31)
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   high_max        366 non-null    float64
 1   low_max         366 non-null    float64
 2   precip_max      366 non-null    float64
 3   snow_max        366 non-null    float64
 4   snowcover_max   366 non-null    float64
 5   high_min        366 non-null    float64
 6   low_min         366 non-null    float64
 7   precip_min      366 non-null    float64
 8   snow_min        366 non-null    float64
 9   snowcover_min   366 non-null    float64
 10  high_mean       366 non-null    float64
 11  low_mean        366 non-null    float64
 12  precip_mean     366 non-null    float64
 13  snow_mean       366 non-null    float64
 14  snowcover_mean  366 non-null    float64
dtypes: float64(15)
memory usage: 45.4 KB</code></pre>
</div>
</div>
<div class="cell" data-cell_id="6ad36954ee874006a56952f3981a559b" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:511}" data-deepnote_cell_type="code" data-execution_millis="2" data-execution_start="1675035885044" data-source_hash="b3f19f13" data-tags="[]" data-execution_count="25">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.merge(df, df_day, on <span class="op">=</span> [<span class="st">'month'</span>, <span class="st">'day'</span>])</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>df.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
Int64Index: 46020 entries, 0 to 46019
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   date            46020 non-null  datetime64[ns]
 1   year            46020 non-null  int64         
 2   month           46020 non-null  int64         
 3   day             46020 non-null  int64         
 4   high            45314 non-null  float64       
 5   low             45255 non-null  float64       
 6   precip          41196 non-null  float64       
 7   snow            25253 non-null  float64       
 8   snowcover       24198 non-null  float64       
 9   high_max        46020 non-null  float64       
 10  low_max         46020 non-null  float64       
 11  precip_max      46020 non-null  float64       
 12  snow_max        46020 non-null  float64       
 13  snowcover_max   46020 non-null  float64       
 14  high_min        46020 non-null  float64       
 15  low_min         46020 non-null  float64       
 16  precip_min      46020 non-null  float64       
 17  snow_min        46020 non-null  float64       
 18  snowcover_min   46020 non-null  float64       
 19  high_mean       46020 non-null  float64       
 20  low_mean        46020 non-null  float64       
 21  precip_mean     46020 non-null  float64       
 22  snow_mean       46020 non-null  float64       
 23  snowcover_mean  46020 non-null  float64       
dtypes: datetime64[ns](1), float64(20), int64(3)
memory usage: 8.8 MB</code></pre>
</div>
</div>
<div class="cell" data-cell_id="9a938cc092c84e7895ca2bd4bc37c6fa" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:517}" data-deepnote_cell_type="code" data-execution_millis="6" data-execution_start="1675035885047" data-source_hash="d62210f6" data-tags="[]" data-execution_count="26">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'high'</span>].fillna(df[<span class="st">'high_mean'</span>], inplace <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'low'</span>].fillna(df[<span class="st">'low_mean'</span>], inplace <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'precip'</span>].fillna(df[<span class="st">'precip_mean'</span>], inplace <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'snow'</span>].fillna(df[<span class="st">'snow_mean'</span>], inplace <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'snowcover'</span>].fillna(df[<span class="st">'snowcover_mean'</span>], inplace <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>df.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
Int64Index: 46020 entries, 0 to 46019
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   date            46020 non-null  datetime64[ns]
 1   year            46020 non-null  int64         
 2   month           46020 non-null  int64         
 3   day             46020 non-null  int64         
 4   high            46020 non-null  float64       
 5   low             46020 non-null  float64       
 6   precip          46020 non-null  float64       
 7   snow            46020 non-null  float64       
 8   snowcover       46020 non-null  float64       
 9   high_max        46020 non-null  float64       
 10  low_max         46020 non-null  float64       
 11  precip_max      46020 non-null  float64       
 12  snow_max        46020 non-null  float64       
 13  snowcover_max   46020 non-null  float64       
 14  high_min        46020 non-null  float64       
 15  low_min         46020 non-null  float64       
 16  precip_min      46020 non-null  float64       
 17  snow_min        46020 non-null  float64       
 18  snowcover_min   46020 non-null  float64       
 19  high_mean       46020 non-null  float64       
 20  low_mean        46020 non-null  float64       
 21  precip_mean     46020 non-null  float64       
 22  snow_mean       46020 non-null  float64       
 23  snowcover_mean  46020 non-null  float64       
dtypes: datetime64[ns](1), float64(20), int64(3)
memory usage: 8.8 MB</code></pre>
</div>
</div>
</section>
<section id="extra-regression" class="level3">
<h3 class="anchored" data-anchor-id="extra-regression">Extra: Regression</h3>
<p>The pandas library does not have a built-in function for filling missing values with regression. However, you can use the scikit-learn library’s LinearRegression class to train a linear regression model on the non-missing data, and then use the trained model to predict the missing values.</p>
<div class="cell" data-cell_id="3044baefec6d47f19b0b96bfd5c813c3" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0}" data-deepnote_cell_type="code" data-execution_millis="12" data-execution_start="1675035885055" data-source_hash="f6b5acb0" data-tags="[]" data-execution_count="27">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.sort_values(by <span class="op">=</span> <span class="st">'date'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="data-understanding" class="level1">
<h1>Data understanding</h1>
<section id="attribute-relations" class="level2">
<h2 class="anchored" data-anchor-id="attribute-relations">Attribute relations</h2>
<div class="cell" data-cell_id="e1516d1e366246dc9af9f899fd677055" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:133}" data-deepnote_cell_type="code" data-execution_millis="5024" data-execution_start="1675035885110" data-outputid="8e9e6b8e-81fa-48f2-93c4-a6f2166fbebb" data-source_hash="111e6f34" data-execution_count="28">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>df.plot(x<span class="op">=</span><span class="st">'date'</span>, y <span class="op">=</span> [<span class="st">'high'</span>,<span class="st">'low'</span>], figsize <span class="op">=</span> (<span class="dv">100</span>, <span class="dv">10</span>))</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>sns.relplot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'date'</span>, y <span class="op">=</span> <span class="st">'high'</span>, col <span class="op">=</span> <span class="st">'month'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-29-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-29-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="cf29ac8d91024287bb24af56d64a5317" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:535}" data-deepnote_cell_type="code" data-execution_millis="989" data-execution_start="1675035890119" data-source_hash="b57e1a65" data-tags="[]" data-execution_count="29">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>df.plot(x<span class="op">=</span><span class="st">'date'</span>, y <span class="op">=</span> [<span class="st">'precip'</span>,<span class="st">'precip_mean'</span>], figsize <span class="op">=</span> (<span class="dv">100</span>, <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="29">
<pre><code>&lt;AxesSubplot: xlabel='date'&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-30-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="d90cb46b84a540c2b714270b98eae3a0" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:541}" data-deepnote_cell_type="code" data-execution_millis="814" data-execution_start="1675035891104" data-source_hash="c6a8025d" data-tags="[]" data-execution_count="30">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>df[df[<span class="st">'year'</span>]<span class="op">==</span><span class="dv">2022</span>].plot(x<span class="op">=</span><span class="st">'date'</span>, y <span class="op">=</span> [<span class="st">'precip'</span>,<span class="st">'precip_mean'</span>], figsize <span class="op">=</span> (<span class="dv">100</span>, <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="30">
<pre><code>&lt;AxesSubplot: xlabel='date'&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-31-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="8ac4235355374fd9929b8c29745176b2" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:529}" data-deepnote_cell_type="code" data-execution_millis="724" data-execution_start="1675035891913" data-source_hash="d7306e6b" data-tags="[]" data-execution_count="31">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>df[df[<span class="st">'year'</span>]<span class="op">==</span><span class="dv">2022</span>].plot(x<span class="op">=</span><span class="st">'date'</span>, y <span class="op">=</span> [<span class="st">'high'</span>,<span class="st">'high_mean'</span>], figsize <span class="op">=</span> (<span class="dv">100</span>, <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">
<pre><code>&lt;AxesSubplot: xlabel='date'&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-32-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="7826bf2f51904cb1a2a07e0bc0232aff" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:547}" data-deepnote_cell_type="code" data-execution_millis="639" data-execution_start="1675035892634" data-source_hash="b91baafe" data-tags="[]" data-execution_count="32">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>df[(df[<span class="st">'month'</span>]<span class="op">==</span><span class="dv">12</span>) <span class="op">&amp;</span> (df[<span class="st">'year'</span>] <span class="op">==</span> <span class="dv">2022</span>)].plot(x<span class="op">=</span><span class="st">'date'</span>, y <span class="op">=</span> [<span class="st">'snow'</span>,<span class="st">'snow_mean'</span>], figsize <span class="op">=</span> (<span class="dv">100</span>, <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="32">
<pre><code>&lt;AxesSubplot: xlabel='date'&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-33-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="a30d14629de34ae484c890df49768239" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:553}" data-deepnote_cell_type="code" data-execution_millis="642" data-execution_start="1675035893275" data-source_hash="f9461ff1" data-tags="[]" data-execution_count="33">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>df[df[<span class="st">'date'</span>] <span class="op">&gt;=</span> np.datetime64(<span class="st">'2022-12-01'</span>)].plot(x<span class="op">=</span><span class="st">'date'</span>, y <span class="op">=</span> [<span class="st">'snow'</span>,<span class="st">'snow_mean'</span>], figsize <span class="op">=</span> (<span class="dv">100</span>, <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="33">
<pre><code>&lt;AxesSubplot: xlabel='date'&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-34-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="3530458b498440009195d0db6d0b8306" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:139}" data-deepnote_cell_type="code" data-execution_millis="6963" data-execution_start="1675035893917" data-outputid="965372ff-068e-45a8-a7f9-0a1bffaa63d9" data-source_hash="8deb0239" data-execution_count="34">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>df.plot(x<span class="op">=</span><span class="st">'date'</span>, y <span class="op">=</span> [<span class="st">'snow'</span>,<span class="st">'snowcover'</span>], figsize <span class="op">=</span> (<span class="dv">100</span>, <span class="dv">10</span>))</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>sns.relplot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'date'</span>, y <span class="op">=</span> <span class="st">'snow'</span>, col <span class="op">=</span> <span class="st">'month'</span>)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>sns.relplot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'date'</span>, y <span class="op">=</span> <span class="st">'snowcover'</span>, col <span class="op">=</span> <span class="st">'month'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-35-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-35-output-2.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-35-output-3.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="b6feccba96594fa68916d4c4a8e99289" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:145}" data-deepnote_cell_type="code" data-execution_millis="2688" data-execution_start="1675035900874" data-outputid="e91f8eb5-1972-4002-81bb-f1839b6c42fb" data-source_hash="47ca1fd0" data-execution_count="35">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>sns.relplot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'high'</span>, y <span class="op">=</span> <span class="st">'low'</span>, col <span class="op">=</span> <span class="st">'month'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-36-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="ee374cc7bed54e338c4af69570b306dc" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:151}" data-deepnote_cell_type="code" data-execution_millis="2474" data-execution_start="1675035903563" data-outputid="14ccc2d5-51eb-4474-e041-948f176c0935" data-source_hash="15f356e1" data-execution_count="36">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>sns.relplot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'snow'</span>, y <span class="op">=</span> <span class="st">'snowcover'</span>, col <span class="op">=</span> <span class="st">'month'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-37-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="0d6a858766214f82a956d9ba1914510b" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:157}" data-deepnote_cell_type="code" data-execution_millis="2" data-execution_start="1675035906040" data-outputid="07528c50-aee9-41d9-e2bf-a0b9f4b4f824" data-source_hash="af5d23cd" data-execution_count="37">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co">#sns.pairplot(data = df)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="distribution-plots" class="level2">
<h2 class="anchored" data-anchor-id="distribution-plots">Distribution plots</h2>
<div class="cell" data-cell_id="224be200424a488ab0c36b523ebfaaba" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:169}" data-deepnote_cell_type="code" data-execution_millis="501" data-execution_start="1675035906046" data-outputid="b7f24e21-394f-4617-8448-513df2d50a4a" data-source_hash="7993bebb" data-execution_count="38">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>sns.displot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'high'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-39-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="234d12b83c344b04b1122a884ee08fc2" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:175}" data-deepnote_cell_type="code" data-execution_millis="3105" data-execution_start="1675035906546" data-outputid="35f45605-e4f0-4051-f96e-4bc2e3d25cf1" data-source_hash="5c3c4525" data-execution_count="39">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>sns.displot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'high'</span>, col <span class="op">=</span> <span class="st">'month'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-40-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="e7bcddfc40dc4411be846e8d6fd08b3b" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:181}" data-deepnote_cell_type="code" data-execution_millis="954" data-execution_start="1675035909652" data-outputid="6249e8f1-5030-4a32-db54-0c0a088d8685" data-source_hash="7958fbd3" data-execution_count="40">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>sns.displot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'high'</span>, hue <span class="op">=</span> <span class="st">'month'</span>, kind <span class="op">=</span> <span class="st">'kde'</span>, multiple <span class="op">=</span> <span class="st">'stack'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-41-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="2af79d48d54d4d67bff915403a7787a9" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:187}" data-deepnote_cell_type="code" data-execution_millis="826" data-execution_start="1675035910607" data-outputid="62278949-5b4d-4913-a852-6df07e68daee" data-source_hash="865d642b" data-execution_count="41">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>sns.displot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'low'</span>, hue <span class="op">=</span> <span class="st">'month'</span>, kind <span class="op">=</span> <span class="st">'kde'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-42-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="797dea259ba04e24a5094e7fffa16377" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:193}" data-deepnote_cell_type="code" data-execution_millis="775" data-execution_start="1675035911411" data-outputid="e94583d2-473f-4775-ed89-dc23999102b0" data-source_hash="5472018d" data-execution_count="42">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>sns.displot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'snow'</span>, hue <span class="op">=</span> <span class="st">'month'</span>, kind <span class="op">=</span> <span class="st">'kde'</span>, multiple <span class="op">=</span> <span class="st">'stack'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-43-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="dcc62aa453ba4d3aa44871e1f3180ee3" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:199}" data-deepnote_cell_type="code" data-execution_millis="866" data-execution_start="1675035912197" data-outputid="9f73f4c3-659a-4f85-d58a-66e916e3ea41" data-source_hash="bbdf815b" data-execution_count="43">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>sns.displot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'snowcover'</span>, hue <span class="op">=</span> <span class="st">'month'</span>, kind <span class="op">=</span> <span class="st">'kde'</span>, multiple <span class="op">=</span> <span class="st">'stack'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-44-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="cb5d0b0cc9c84cea82010e8191757453" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:205}" data-deepnote_cell_type="code" data-execution_millis="29802" data-execution_start="1675035913065" data-outputid="fc41c236-a85e-48fd-ee65-928fcbd2b3c1" data-source_hash="27159cf9" data-execution_count="44">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>sns.displot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'high'</span>, y <span class="op">=</span> <span class="st">'low'</span>, hue <span class="op">=</span> <span class="st">'month'</span>, kind <span class="op">=</span> <span class="st">'kde'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-45-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="7be9506fa9a641ff8680f7db4043bf36" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:211}" data-deepnote_cell_type="code" data-execution_millis="23224" data-execution_start="1675035942865" data-outputid="293649c9-1a77-4c79-a45a-aa747a06808f" data-source_hash="ccb3f852" data-execution_count="45">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>sns.displot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'snow'</span>, y <span class="op">=</span> <span class="st">'snowcover'</span>, hue <span class="op">=</span> <span class="st">'month'</span>, kind <span class="op">=</span> <span class="st">'kde'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-46-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
</section>
<section id="data-preprocessing" class="level1">
<h1>Data preprocessing</h1>
<section id="create-a-new-attribute-tavg" class="level2">
<h2 class="anchored" data-anchor-id="create-a-new-attribute-tavg">Create a new attribute, tavg</h2>
<p>We may want to get the average temperature of the day, rather than max and min.</p>
<div class="cell" data-cell_id="48f9a726a318488c8bf0607f44009247" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:229}" data-deepnote_cell_type="code" data-execution_millis="382" data-execution_start="1675035966082" data-outputid="699f633d-cc3e-4bb6-8267-5fd53b044aa1" data-source_hash="de4463a2" data-execution_count="46">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>sns.displot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'high'</span>, kind <span class="op">=</span> <span class="st">'hist'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-47-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="260c81c72c1647b1bdf7319a195b1813" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:235}" data-deepnote_cell_type="code" data-execution_millis="451" data-execution_start="1675035966464" data-outputid="5d83a118-a4c1-408e-8da4-3903fcd375bf" data-source_hash="d7b8bf30" data-execution_count="47">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>sns.displot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'low'</span>, kind <span class="op">=</span> <span class="st">'hist'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-48-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="32c6d1988d334aada38a41905ba9a95b" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:241}" data-deepnote_cell_type="code" data-execution_millis="13" data-execution_start="1675035966921" data-outputid="abdb18b1-68d3-4293-af7e-e767fe2fa428" data-source_hash="bb3d21ca" data-execution_count="48">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'tavg'</span>] <span class="op">=</span> (df[<span class="st">'high'</span>] <span class="op">+</span> df[<span class="st">'low'</span>]) <span class="op">/</span> <span class="dv">2</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>df.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
Int64Index: 46020 entries, 0 to 45989
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   date            46020 non-null  datetime64[ns]
 1   year            46020 non-null  int64         
 2   month           46020 non-null  int64         
 3   day             46020 non-null  int64         
 4   high            46020 non-null  float64       
 5   low             46020 non-null  float64       
 6   precip          46020 non-null  float64       
 7   snow            46020 non-null  float64       
 8   snowcover       46020 non-null  float64       
 9   high_max        46020 non-null  float64       
 10  low_max         46020 non-null  float64       
 11  precip_max      46020 non-null  float64       
 12  snow_max        46020 non-null  float64       
 13  snowcover_max   46020 non-null  float64       
 14  high_min        46020 non-null  float64       
 15  low_min         46020 non-null  float64       
 16  precip_min      46020 non-null  float64       
 17  snow_min        46020 non-null  float64       
 18  snowcover_min   46020 non-null  float64       
 19  high_mean       46020 non-null  float64       
 20  low_mean        46020 non-null  float64       
 21  precip_mean     46020 non-null  float64       
 22  snow_mean       46020 non-null  float64       
 23  snowcover_mean  46020 non-null  float64       
 24  tavg            46020 non-null  float64       
dtypes: datetime64[ns](1), float64(21), int64(3)
memory usage: 10.1 MB</code></pre>
</div>
</div>
<div class="cell" data-cell_id="9117dec84bdb4c34bfed950d18a189aa" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:247}" data-deepnote_cell_type="code" data-execution_millis="505" data-execution_start="1675035966939" data-outputid="5211ef54-69cd-48f8-f30a-4f706278a164" data-source_hash="990c0ed1" data-execution_count="49">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>sns.displot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'tavg'</span>, kind <span class="op">=</span> <span class="st">'hist'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-50-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="9952d537b77d424690c3eafa19498172" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:253}" data-deepnote_cell_type="code" data-execution_millis="1143" data-execution_start="1675035967449" data-outputid="de4becbd-1b92-4249-e590-190eefbad161" data-source_hash="520f0503" data-execution_count="50">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>sns.displot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'tavg'</span>, hue <span class="op">=</span> <span class="st">'month'</span>, kind <span class="op">=</span> <span class="st">'kde'</span>, multiple <span class="op">=</span> <span class="st">'stack'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-51-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="create-a-new-attribute-weather" class="level2">
<h2 class="anchored" data-anchor-id="create-a-new-attribute-weather">Create a new attribute, weather</h2>
<p>We may want to include a weather condition based on the precip, snow, and snowcover.</p>
<div class="cell" data-cell_id="3a3d8e0e5c8c4aae9377f078e8e47bff" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:265}" data-deepnote_cell_type="code" data-execution_millis="4" data-execution_start="1675035968588" data-outputid="d10a8a16-33f4-45a9-8081-e599dafdddf0" data-source_hash="aa0c1dcf" data-execution_count="51">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>conditions <span class="op">=</span> [</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>    (df[<span class="st">'precip'</span>] <span class="op">==</span><span class="dv">0</span>),</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>    (df[<span class="st">'precip'</span>] <span class="op">&gt;</span> <span class="dv">0</span>) <span class="op">&amp;</span> (df[<span class="st">'snow'</span>] <span class="op">==</span><span class="dv">0</span>),</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>    (df[<span class="st">'precip'</span>] <span class="op">&gt;</span> <span class="dv">0</span>) <span class="op">&amp;</span> (df[<span class="st">'snow'</span>] <span class="op">&gt;</span> <span class="dv">0</span>),</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>values <span class="op">=</span> [<span class="st">'sunny'</span>, <span class="st">'rain'</span>, <span class="st">'snow'</span>]</span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'weather'</span>] <span class="op">=</span> np.select(conditions, values)</span>
<span id="cb69-10"><a href="#cb69-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-11"><a href="#cb69-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-12"><a href="#cb69-12" aria-hidden="true" tabindex="-1"></a>df.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
Int64Index: 46020 entries, 0 to 45989
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   date            46020 non-null  datetime64[ns]
 1   year            46020 non-null  int64         
 2   month           46020 non-null  int64         
 3   day             46020 non-null  int64         
 4   high            46020 non-null  float64       
 5   low             46020 non-null  float64       
 6   precip          46020 non-null  float64       
 7   snow            46020 non-null  float64       
 8   snowcover       46020 non-null  float64       
 9   high_max        46020 non-null  float64       
 10  low_max         46020 non-null  float64       
 11  precip_max      46020 non-null  float64       
 12  snow_max        46020 non-null  float64       
 13  snowcover_max   46020 non-null  float64       
 14  high_min        46020 non-null  float64       
 15  low_min         46020 non-null  float64       
 16  precip_min      46020 non-null  float64       
 17  snow_min        46020 non-null  float64       
 18  snowcover_min   46020 non-null  float64       
 19  high_mean       46020 non-null  float64       
 20  low_mean        46020 non-null  float64       
 21  precip_mean     46020 non-null  float64       
 22  snow_mean       46020 non-null  float64       
 23  snowcover_mean  46020 non-null  float64       
 24  tavg            46020 non-null  float64       
 25  weather         46020 non-null  object        
dtypes: datetime64[ns](1), float64(21), int64(3), object(1)
memory usage: 10.5+ MB</code></pre>
</div>
</div>
<div class="cell" data-cell_id="1d1641f52728442b842ba45946f7c536" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:271}" data-deepnote_cell_type="code" data-execution_millis="3" data-execution_start="1675035968611" data-outputid="c8014d23-3d48-4c66-c6e9-8d6c152de3d5" data-source_hash="cffadf02" data-execution_count="52">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'weather'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="52">
<pre><code>sunny    30345
rain      8802
snow      6873
Name: weather, dtype: int64</code></pre>
</div>
</div>
<div class="cell" data-cell_id="a54bc5f121934f32881152b3e93e7017" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:277}" data-deepnote_cell_type="code" data-execution_millis="461" data-execution_start="1675035968612" data-outputid="a7040ae3-456c-4a7b-c70a-a48250838232" data-source_hash="b2d015a" data-execution_count="53">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>sns.catplot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'weather'</span>, y <span class="op">=</span> <span class="st">'tavg'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-54-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="a1cd62d59bb24c5d93d3d0ea9aede219" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:283}" data-deepnote_cell_type="code" data-execution_millis="1535" data-execution_start="1675035969076" data-outputid="620bdd89-6f30-474f-9595-8029328e8c73" data-source_hash="a642265c" data-execution_count="54">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>sns.catplot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'weather'</span>, y <span class="op">=</span> <span class="st">'tavg'</span>, kind <span class="op">=</span> <span class="st">'violin'</span>, hue <span class="op">=</span> <span class="st">'month'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-55-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="eb5f64bcb5f346b89f0b4f73a6d80b27" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:289}" data-deepnote_cell_type="code" data-execution_millis="466" data-execution_start="1675035970612" data-outputid="80e6a0f8-63bd-456c-ab71-7638b3109d0d" data-source_hash="ac19546d" data-execution_count="55">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>sns.catplot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'weather'</span>, y <span class="op">=</span> <span class="st">'snow'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-56-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="66c3edf6dba942f89d7e35a8ff467ca2" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:295}" data-deepnote_cell_type="code" data-execution_millis="1089" data-execution_start="1675035971081" data-outputid="62787d56-098e-401c-e22a-bf03da391c7c" data-source_hash="cd184211" data-execution_count="56">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>sns.catplot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'weather'</span>, y <span class="op">=</span> <span class="st">'snow'</span>, kind <span class="op">=</span> <span class="st">'violin'</span>, hue <span class="op">=</span> <span class="st">'month'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-57-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="ecb31017743f4c14ab0cb6f29c2120d4" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:301}" data-deepnote_cell_type="code" data-execution_millis="244" data-execution_start="1675035972180" data-outputid="99d1912b-ec87-436b-deea-49032fc26821" data-source_hash="9f7e3043" data-execution_count="57">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>pd.DataFrame({<span class="st">"weather"</span> : df[<span class="st">'weather'</span>].value_counts()}).plot.pie(y<span class="op">=</span> <span class="st">"weather"</span>, figsize <span class="op">=</span> (<span class="dv">5</span>, <span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="57">
<pre><code>&lt;AxesSubplot: ylabel='weather'&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-58-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="10102ae5eb1f459fabf54997f765b97f" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:307}" data-deepnote_cell_type="code" data-execution_millis="1099" data-execution_start="1675035972427" data-outputid="9c74a0f6-f1d2-4177-cde0-bb66c6583009" data-source_hash="9b88cb29" data-execution_count="58">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>sns.catplot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'month'</span>, y <span class="op">=</span> <span class="st">'tavg'</span>, kind <span class="op">=</span> <span class="st">'box'</span>, col <span class="op">=</span> <span class="st">'weather'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-59-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="6e16047da2804c23b924f229549cec51" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:313}" data-deepnote_cell_type="code" data-execution_millis="400" data-execution_start="1675035973538" data-outputid="8c15a88b-695d-4412-ef7f-15cc33414ad5" data-source_hash="642cfe18" data-execution_count="59">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>df.boxplot(column <span class="op">=</span> [<span class="st">'tavg'</span>], by <span class="op">=</span>[<span class="st">'month'</span>], figsize <span class="op">=</span> (<span class="dv">30</span>, <span class="dv">10</span>))</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">90</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="59">
<pre><code>(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 [Text(1, 0, '1'),
  Text(2, 0, '2'),
  Text(3, 0, '3'),
  Text(4, 0, '4'),
  Text(5, 0, '5'),
  Text(6, 0, '6'),
  Text(7, 0, '7'),
  Text(8, 0, '8'),
  Text(9, 0, '9'),
  Text(10, 0, '10'),
  Text(11, 0, '11'),
  Text(12, 0, '12')])</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-60-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="d9368225f93c4963860e4c299120a085" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:319}" data-deepnote_cell_type="code" data-execution_millis="4839" data-execution_start="1675035974117" data-outputid="20ceb9fe-47db-4727-eefe-5a101a54008e" data-source_hash="81ca5817" data-execution_count="60">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>df.boxplot(column <span class="op">=</span> [<span class="st">'tavg'</span>], by <span class="op">=</span>[<span class="st">'month'</span>, <span class="st">'day'</span>], figsize <span class="op">=</span> (<span class="dv">100</span>, <span class="dv">10</span>))</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">90</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="60">
<pre><code>(array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
        105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
        118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
        131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
        144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
        170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
        183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
        196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208,
        209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,
        222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234,
        235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247,
        248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260,
        261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273,
        274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286,
        287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299,
        300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312,
        313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325,
        326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338,
        339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351,
        352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364,
        365, 366]),
 [Text(1, 0, '(1, 1)'),
  Text(2, 0, '(1, 2)'),
  Text(3, 0, '(1, 3)'),
  Text(4, 0, '(1, 4)'),
  Text(5, 0, '(1, 5)'),
  Text(6, 0, '(1, 6)'),
  Text(7, 0, '(1, 7)'),
  Text(8, 0, '(1, 8)'),
  Text(9, 0, '(1, 9)'),
  Text(10, 0, '(1, 10)'),
  Text(11, 0, '(1, 11)'),
  Text(12, 0, '(1, 12)'),
  Text(13, 0, '(1, 13)'),
  Text(14, 0, '(1, 14)'),
  Text(15, 0, '(1, 15)'),
  Text(16, 0, '(1, 16)'),
  Text(17, 0, '(1, 17)'),
  Text(18, 0, '(1, 18)'),
  Text(19, 0, '(1, 19)'),
  Text(20, 0, '(1, 20)'),
  Text(21, 0, '(1, 21)'),
  Text(22, 0, '(1, 22)'),
  Text(23, 0, '(1, 23)'),
  Text(24, 0, '(1, 24)'),
  Text(25, 0, '(1, 25)'),
  Text(26, 0, '(1, 26)'),
  Text(27, 0, '(1, 27)'),
  Text(28, 0, '(1, 28)'),
  Text(29, 0, '(1, 29)'),
  Text(30, 0, '(1, 30)'),
  Text(31, 0, '(1, 31)'),
  Text(32, 0, '(2, 1)'),
  Text(33, 0, '(2, 2)'),
  Text(34, 0, '(2, 3)'),
  Text(35, 0, '(2, 4)'),
  Text(36, 0, '(2, 5)'),
  Text(37, 0, '(2, 6)'),
  Text(38, 0, '(2, 7)'),
  Text(39, 0, '(2, 8)'),
  Text(40, 0, '(2, 9)'),
  Text(41, 0, '(2, 10)'),
  Text(42, 0, '(2, 11)'),
  Text(43, 0, '(2, 12)'),
  Text(44, 0, '(2, 13)'),
  Text(45, 0, '(2, 14)'),
  Text(46, 0, '(2, 15)'),
  Text(47, 0, '(2, 16)'),
  Text(48, 0, '(2, 17)'),
  Text(49, 0, '(2, 18)'),
  Text(50, 0, '(2, 19)'),
  Text(51, 0, '(2, 20)'),
  Text(52, 0, '(2, 21)'),
  Text(53, 0, '(2, 22)'),
  Text(54, 0, '(2, 23)'),
  Text(55, 0, '(2, 24)'),
  Text(56, 0, '(2, 25)'),
  Text(57, 0, '(2, 26)'),
  Text(58, 0, '(2, 27)'),
  Text(59, 0, '(2, 28)'),
  Text(60, 0, '(2, 29)'),
  Text(61, 0, '(3, 1)'),
  Text(62, 0, '(3, 2)'),
  Text(63, 0, '(3, 3)'),
  Text(64, 0, '(3, 4)'),
  Text(65, 0, '(3, 5)'),
  Text(66, 0, '(3, 6)'),
  Text(67, 0, '(3, 7)'),
  Text(68, 0, '(3, 8)'),
  Text(69, 0, '(3, 9)'),
  Text(70, 0, '(3, 10)'),
  Text(71, 0, '(3, 11)'),
  Text(72, 0, '(3, 12)'),
  Text(73, 0, '(3, 13)'),
  Text(74, 0, '(3, 14)'),
  Text(75, 0, '(3, 15)'),
  Text(76, 0, '(3, 16)'),
  Text(77, 0, '(3, 17)'),
  Text(78, 0, '(3, 18)'),
  Text(79, 0, '(3, 19)'),
  Text(80, 0, '(3, 20)'),
  Text(81, 0, '(3, 21)'),
  Text(82, 0, '(3, 22)'),
  Text(83, 0, '(3, 23)'),
  Text(84, 0, '(3, 24)'),
  Text(85, 0, '(3, 25)'),
  Text(86, 0, '(3, 26)'),
  Text(87, 0, '(3, 27)'),
  Text(88, 0, '(3, 28)'),
  Text(89, 0, '(3, 29)'),
  Text(90, 0, '(3, 30)'),
  Text(91, 0, '(3, 31)'),
  Text(92, 0, '(4, 1)'),
  Text(93, 0, '(4, 2)'),
  Text(94, 0, '(4, 3)'),
  Text(95, 0, '(4, 4)'),
  Text(96, 0, '(4, 5)'),
  Text(97, 0, '(4, 6)'),
  Text(98, 0, '(4, 7)'),
  Text(99, 0, '(4, 8)'),
  Text(100, 0, '(4, 9)'),
  Text(101, 0, '(4, 10)'),
  Text(102, 0, '(4, 11)'),
  Text(103, 0, '(4, 12)'),
  Text(104, 0, '(4, 13)'),
  Text(105, 0, '(4, 14)'),
  Text(106, 0, '(4, 15)'),
  Text(107, 0, '(4, 16)'),
  Text(108, 0, '(4, 17)'),
  Text(109, 0, '(4, 18)'),
  Text(110, 0, '(4, 19)'),
  Text(111, 0, '(4, 20)'),
  Text(112, 0, '(4, 21)'),
  Text(113, 0, '(4, 22)'),
  Text(114, 0, '(4, 23)'),
  Text(115, 0, '(4, 24)'),
  Text(116, 0, '(4, 25)'),
  Text(117, 0, '(4, 26)'),
  Text(118, 0, '(4, 27)'),
  Text(119, 0, '(4, 28)'),
  Text(120, 0, '(4, 29)'),
  Text(121, 0, '(4, 30)'),
  Text(122, 0, '(5, 1)'),
  Text(123, 0, '(5, 2)'),
  Text(124, 0, '(5, 3)'),
  Text(125, 0, '(5, 4)'),
  Text(126, 0, '(5, 5)'),
  Text(127, 0, '(5, 6)'),
  Text(128, 0, '(5, 7)'),
  Text(129, 0, '(5, 8)'),
  Text(130, 0, '(5, 9)'),
  Text(131, 0, '(5, 10)'),
  Text(132, 0, '(5, 11)'),
  Text(133, 0, '(5, 12)'),
  Text(134, 0, '(5, 13)'),
  Text(135, 0, '(5, 14)'),
  Text(136, 0, '(5, 15)'),
  Text(137, 0, '(5, 16)'),
  Text(138, 0, '(5, 17)'),
  Text(139, 0, '(5, 18)'),
  Text(140, 0, '(5, 19)'),
  Text(141, 0, '(5, 20)'),
  Text(142, 0, '(5, 21)'),
  Text(143, 0, '(5, 22)'),
  Text(144, 0, '(5, 23)'),
  Text(145, 0, '(5, 24)'),
  Text(146, 0, '(5, 25)'),
  Text(147, 0, '(5, 26)'),
  Text(148, 0, '(5, 27)'),
  Text(149, 0, '(5, 28)'),
  Text(150, 0, '(5, 29)'),
  Text(151, 0, '(5, 30)'),
  Text(152, 0, '(5, 31)'),
  Text(153, 0, '(6, 1)'),
  Text(154, 0, '(6, 2)'),
  Text(155, 0, '(6, 3)'),
  Text(156, 0, '(6, 4)'),
  Text(157, 0, '(6, 5)'),
  Text(158, 0, '(6, 6)'),
  Text(159, 0, '(6, 7)'),
  Text(160, 0, '(6, 8)'),
  Text(161, 0, '(6, 9)'),
  Text(162, 0, '(6, 10)'),
  Text(163, 0, '(6, 11)'),
  Text(164, 0, '(6, 12)'),
  Text(165, 0, '(6, 13)'),
  Text(166, 0, '(6, 14)'),
  Text(167, 0, '(6, 15)'),
  Text(168, 0, '(6, 16)'),
  Text(169, 0, '(6, 17)'),
  Text(170, 0, '(6, 18)'),
  Text(171, 0, '(6, 19)'),
  Text(172, 0, '(6, 20)'),
  Text(173, 0, '(6, 21)'),
  Text(174, 0, '(6, 22)'),
  Text(175, 0, '(6, 23)'),
  Text(176, 0, '(6, 24)'),
  Text(177, 0, '(6, 25)'),
  Text(178, 0, '(6, 26)'),
  Text(179, 0, '(6, 27)'),
  Text(180, 0, '(6, 28)'),
  Text(181, 0, '(6, 29)'),
  Text(182, 0, '(6, 30)'),
  Text(183, 0, '(7, 1)'),
  Text(184, 0, '(7, 2)'),
  Text(185, 0, '(7, 3)'),
  Text(186, 0, '(7, 4)'),
  Text(187, 0, '(7, 5)'),
  Text(188, 0, '(7, 6)'),
  Text(189, 0, '(7, 7)'),
  Text(190, 0, '(7, 8)'),
  Text(191, 0, '(7, 9)'),
  Text(192, 0, '(7, 10)'),
  Text(193, 0, '(7, 11)'),
  Text(194, 0, '(7, 12)'),
  Text(195, 0, '(7, 13)'),
  Text(196, 0, '(7, 14)'),
  Text(197, 0, '(7, 15)'),
  Text(198, 0, '(7, 16)'),
  Text(199, 0, '(7, 17)'),
  Text(200, 0, '(7, 18)'),
  Text(201, 0, '(7, 19)'),
  Text(202, 0, '(7, 20)'),
  Text(203, 0, '(7, 21)'),
  Text(204, 0, '(7, 22)'),
  Text(205, 0, '(7, 23)'),
  Text(206, 0, '(7, 24)'),
  Text(207, 0, '(7, 25)'),
  Text(208, 0, '(7, 26)'),
  Text(209, 0, '(7, 27)'),
  Text(210, 0, '(7, 28)'),
  Text(211, 0, '(7, 29)'),
  Text(212, 0, '(7, 30)'),
  Text(213, 0, '(7, 31)'),
  Text(214, 0, '(8, 1)'),
  Text(215, 0, '(8, 2)'),
  Text(216, 0, '(8, 3)'),
  Text(217, 0, '(8, 4)'),
  Text(218, 0, '(8, 5)'),
  Text(219, 0, '(8, 6)'),
  Text(220, 0, '(8, 7)'),
  Text(221, 0, '(8, 8)'),
  Text(222, 0, '(8, 9)'),
  Text(223, 0, '(8, 10)'),
  Text(224, 0, '(8, 11)'),
  Text(225, 0, '(8, 12)'),
  Text(226, 0, '(8, 13)'),
  Text(227, 0, '(8, 14)'),
  Text(228, 0, '(8, 15)'),
  Text(229, 0, '(8, 16)'),
  Text(230, 0, '(8, 17)'),
  Text(231, 0, '(8, 18)'),
  Text(232, 0, '(8, 19)'),
  Text(233, 0, '(8, 20)'),
  Text(234, 0, '(8, 21)'),
  Text(235, 0, '(8, 22)'),
  Text(236, 0, '(8, 23)'),
  Text(237, 0, '(8, 24)'),
  Text(238, 0, '(8, 25)'),
  Text(239, 0, '(8, 26)'),
  Text(240, 0, '(8, 27)'),
  Text(241, 0, '(8, 28)'),
  Text(242, 0, '(8, 29)'),
  Text(243, 0, '(8, 30)'),
  Text(244, 0, '(8, 31)'),
  Text(245, 0, '(9, 1)'),
  Text(246, 0, '(9, 2)'),
  Text(247, 0, '(9, 3)'),
  Text(248, 0, '(9, 4)'),
  Text(249, 0, '(9, 5)'),
  Text(250, 0, '(9, 6)'),
  Text(251, 0, '(9, 7)'),
  Text(252, 0, '(9, 8)'),
  Text(253, 0, '(9, 9)'),
  Text(254, 0, '(9, 10)'),
  Text(255, 0, '(9, 11)'),
  Text(256, 0, '(9, 12)'),
  Text(257, 0, '(9, 13)'),
  Text(258, 0, '(9, 14)'),
  Text(259, 0, '(9, 15)'),
  Text(260, 0, '(9, 16)'),
  Text(261, 0, '(9, 17)'),
  Text(262, 0, '(9, 18)'),
  Text(263, 0, '(9, 19)'),
  Text(264, 0, '(9, 20)'),
  Text(265, 0, '(9, 21)'),
  Text(266, 0, '(9, 22)'),
  Text(267, 0, '(9, 23)'),
  Text(268, 0, '(9, 24)'),
  Text(269, 0, '(9, 25)'),
  Text(270, 0, '(9, 26)'),
  Text(271, 0, '(9, 27)'),
  Text(272, 0, '(9, 28)'),
  Text(273, 0, '(9, 29)'),
  Text(274, 0, '(9, 30)'),
  Text(275, 0, '(10, 1)'),
  Text(276, 0, '(10, 2)'),
  Text(277, 0, '(10, 3)'),
  Text(278, 0, '(10, 4)'),
  Text(279, 0, '(10, 5)'),
  Text(280, 0, '(10, 6)'),
  Text(281, 0, '(10, 7)'),
  Text(282, 0, '(10, 8)'),
  Text(283, 0, '(10, 9)'),
  Text(284, 0, '(10, 10)'),
  Text(285, 0, '(10, 11)'),
  Text(286, 0, '(10, 12)'),
  Text(287, 0, '(10, 13)'),
  Text(288, 0, '(10, 14)'),
  Text(289, 0, '(10, 15)'),
  Text(290, 0, '(10, 16)'),
  Text(291, 0, '(10, 17)'),
  Text(292, 0, '(10, 18)'),
  Text(293, 0, '(10, 19)'),
  Text(294, 0, '(10, 20)'),
  Text(295, 0, '(10, 21)'),
  Text(296, 0, '(10, 22)'),
  Text(297, 0, '(10, 23)'),
  Text(298, 0, '(10, 24)'),
  Text(299, 0, '(10, 25)'),
  Text(300, 0, '(10, 26)'),
  Text(301, 0, '(10, 27)'),
  Text(302, 0, '(10, 28)'),
  Text(303, 0, '(10, 29)'),
  Text(304, 0, '(10, 30)'),
  Text(305, 0, '(10, 31)'),
  Text(306, 0, '(11, 1)'),
  Text(307, 0, '(11, 2)'),
  Text(308, 0, '(11, 3)'),
  Text(309, 0, '(11, 4)'),
  Text(310, 0, '(11, 5)'),
  Text(311, 0, '(11, 6)'),
  Text(312, 0, '(11, 7)'),
  Text(313, 0, '(11, 8)'),
  Text(314, 0, '(11, 9)'),
  Text(315, 0, '(11, 10)'),
  Text(316, 0, '(11, 11)'),
  Text(317, 0, '(11, 12)'),
  Text(318, 0, '(11, 13)'),
  Text(319, 0, '(11, 14)'),
  Text(320, 0, '(11, 15)'),
  Text(321, 0, '(11, 16)'),
  Text(322, 0, '(11, 17)'),
  Text(323, 0, '(11, 18)'),
  Text(324, 0, '(11, 19)'),
  Text(325, 0, '(11, 20)'),
  Text(326, 0, '(11, 21)'),
  Text(327, 0, '(11, 22)'),
  Text(328, 0, '(11, 23)'),
  Text(329, 0, '(11, 24)'),
  Text(330, 0, '(11, 25)'),
  Text(331, 0, '(11, 26)'),
  Text(332, 0, '(11, 27)'),
  Text(333, 0, '(11, 28)'),
  Text(334, 0, '(11, 29)'),
  Text(335, 0, '(11, 30)'),
  Text(336, 0, '(12, 1)'),
  Text(337, 0, '(12, 2)'),
  Text(338, 0, '(12, 3)'),
  Text(339, 0, '(12, 4)'),
  Text(340, 0, '(12, 5)'),
  Text(341, 0, '(12, 6)'),
  Text(342, 0, '(12, 7)'),
  Text(343, 0, '(12, 8)'),
  Text(344, 0, '(12, 9)'),
  Text(345, 0, '(12, 10)'),
  Text(346, 0, '(12, 11)'),
  Text(347, 0, '(12, 12)'),
  Text(348, 0, '(12, 13)'),
  Text(349, 0, '(12, 14)'),
  Text(350, 0, '(12, 15)'),
  Text(351, 0, '(12, 16)'),
  Text(352, 0, '(12, 17)'),
  Text(353, 0, '(12, 18)'),
  Text(354, 0, '(12, 19)'),
  Text(355, 0, '(12, 20)'),
  Text(356, 0, '(12, 21)'),
  Text(357, 0, '(12, 22)'),
  Text(358, 0, '(12, 23)'),
  Text(359, 0, '(12, 24)'),
  Text(360, 0, '(12, 25)'),
  Text(361, 0, '(12, 26)'),
  Text(362, 0, '(12, 27)'),
  Text(363, 0, '(12, 28)'),
  Text(364, 0, '(12, 29)'),
  Text(365, 0, '(12, 30)'),
  Text(366, 0, '(12, 31)')])</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-61-output-2.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="create-a-new-attribute-season" class="level2">
<h2 class="anchored" data-anchor-id="create-a-new-attribute-season">Create a new attribute, season</h2>
<div class="cell" data-cell_id="4ddfb0927188488cbb9b03a963ad170e" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:331}" data-deepnote_cell_type="code" data-execution_millis="77" data-execution_start="1675035978953" data-outputid="0bf7d3af-c57d-433e-ec90-ded025e0f244" data-source_hash="f33dc409" data-execution_count="61">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>conditions <span class="op">=</span> [</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>    (df[<span class="st">'month'</span>] <span class="op">==</span> <span class="dv">12</span>) <span class="op">|</span> (df[<span class="st">'month'</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">|</span> (df[<span class="st">'month'</span>] <span class="op">==</span> <span class="dv">2</span>), </span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>    (df[<span class="st">'month'</span>] <span class="op">==</span> <span class="dv">3</span>) <span class="op">|</span> (df[<span class="st">'month'</span>] <span class="op">==</span> <span class="dv">4</span>) <span class="op">|</span> (df[<span class="st">'month'</span>] <span class="op">==</span> <span class="dv">5</span>),</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>    (df[<span class="st">'month'</span>] <span class="op">==</span> <span class="dv">6</span>) <span class="op">|</span> (df[<span class="st">'month'</span>] <span class="op">==</span> <span class="dv">7</span>) <span class="op">|</span> (df[<span class="st">'month'</span>] <span class="op">==</span> <span class="dv">8</span>),</span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>    (df[<span class="st">'month'</span>] <span class="op">==</span> <span class="dv">9</span>) <span class="op">|</span> (df[<span class="st">'month'</span>] <span class="op">==</span> <span class="dv">10</span>) <span class="op">|</span> (df[<span class="st">'month'</span>] <span class="op">==</span> <span class="dv">11</span>),</span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-8"><a href="#cb84-8" aria-hidden="true" tabindex="-1"></a>values <span class="op">=</span> [<span class="st">'winter'</span>, <span class="st">'spring'</span>, <span class="st">'summer'</span>, <span class="st">'fall'</span>]</span>
<span id="cb84-9"><a href="#cb84-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-10"><a href="#cb84-10" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'season'</span>] <span class="op">=</span> np.select(conditions, values)</span>
<span id="cb84-11"><a href="#cb84-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-12"><a href="#cb84-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-13"><a href="#cb84-13" aria-hidden="true" tabindex="-1"></a>df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="61">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">date</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">month</th>
<th data-quarto-table-cell-role="th">day</th>
<th data-quarto-table-cell-role="th">high</th>
<th data-quarto-table-cell-role="th">low</th>
<th data-quarto-table-cell-role="th">precip</th>
<th data-quarto-table-cell-role="th">snow</th>
<th data-quarto-table-cell-role="th">snowcover</th>
<th data-quarto-table-cell-role="th">high_max</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">snow_min</th>
<th data-quarto-table-cell-role="th">snowcover_min</th>
<th data-quarto-table-cell-role="th">high_mean</th>
<th data-quarto-table-cell-role="th">low_mean</th>
<th data-quarto-table-cell-role="th">precip_mean</th>
<th data-quarto-table-cell-role="th">snow_mean</th>
<th data-quarto-table-cell-role="th">snowcover_mean</th>
<th data-quarto-table-cell-role="th">tavg</th>
<th data-quarto-table-cell-role="th">weather</th>
<th data-quarto-table-cell-role="th">season</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1897-01-01</td>
<td>1897</td>
<td>1</td>
<td>1</td>
<td>41.243902</td>
<td>18.747967</td>
<td>0.025478</td>
<td>0.529851</td>
<td>2.152542</td>
<td>70.0</td>
<td>...</td>
<td>0.0</td>
<td>0.0</td>
<td>41.243902</td>
<td>18.747967</td>
<td>0.025478</td>
<td>0.529851</td>
<td>2.152542</td>
<td>29.995935</td>
<td>snow</td>
<td>winter</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">126</td>
<td>1897-01-02</td>
<td>1897</td>
<td>1</td>
<td>2</td>
<td>43.715447</td>
<td>17.861789</td>
<td>0.011441</td>
<td>0.294203</td>
<td>1.968254</td>
<td>70.0</td>
<td>...</td>
<td>0.0</td>
<td>0.0</td>
<td>43.715447</td>
<td>17.861789</td>
<td>0.011441</td>
<td>0.294203</td>
<td>1.968254</td>
<td>30.788618</td>
<td>snow</td>
<td>winter</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">252</td>
<td>1897-01-03</td>
<td>1897</td>
<td>1</td>
<td>3</td>
<td>43.780488</td>
<td>19.634146</td>
<td>0.025424</td>
<td>0.453623</td>
<td>2.351852</td>
<td>68.0</td>
<td>...</td>
<td>0.0</td>
<td>0.0</td>
<td>43.780488</td>
<td>19.634146</td>
<td>0.025424</td>
<td>0.453623</td>
<td>2.351852</td>
<td>31.707317</td>
<td>snow</td>
<td>winter</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">378</td>
<td>1897-01-04</td>
<td>1897</td>
<td>1</td>
<td>4</td>
<td>43.943089</td>
<td>19.918699</td>
<td>0.028509</td>
<td>0.523077</td>
<td>2.322034</td>
<td>67.0</td>
<td>...</td>
<td>0.0</td>
<td>0.0</td>
<td>43.943089</td>
<td>19.918699</td>
<td>0.028509</td>
<td>0.523077</td>
<td>2.322034</td>
<td>31.930894</td>
<td>snow</td>
<td>winter</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">504</td>
<td>1897-01-05</td>
<td>1897</td>
<td>1</td>
<td>5</td>
<td>44.691057</td>
<td>20.146341</td>
<td>0.026991</td>
<td>0.557812</td>
<td>2.410714</td>
<td>69.0</td>
<td>...</td>
<td>0.0</td>
<td>0.0</td>
<td>44.691057</td>
<td>20.146341</td>
<td>0.026991</td>
<td>0.557812</td>
<td>2.410714</td>
<td>32.418699</td>
<td>snow</td>
<td>winter</td>
</tr>
</tbody>
</table>

<p>5 rows × 27 columns</p>
</div>
</div>
</div>
<div class="cell" data-cell_id="9512234da5de4306827cce0708ba1ce0" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:337}" data-deepnote_cell_type="code" data-execution_millis="1243" data-execution_start="1675035979030" data-outputid="c8e8716f-4ce3-4dc9-a639-802aa21bc3d1" data-source_hash="f1a1da9e" data-execution_count="62">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>sns.displot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'tavg'</span>, kind <span class="op">=</span> <span class="st">'kde'</span>, multiple <span class="op">=</span> <span class="st">'stack'</span>, hue <span class="op">=</span> <span class="st">'season'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-63-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="9570c0d81e8c44c4a29827b353b30f8e" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:343}" data-deepnote_cell_type="code" data-execution_millis="472" data-execution_start="1675035980273" data-outputid="ca365363-7491-41ca-8118-4bb60abfcf4d" data-source_hash="546f634c" data-execution_count="63">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>sns.catplot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'season'</span>, y <span class="op">=</span> <span class="st">'tavg'</span>, kind <span class="op">=</span> <span class="st">'box'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-64-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="5c2ac1b0328b4b1090647ec46d36bb40" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:349}" data-deepnote_cell_type="code" data-execution_millis="915" data-execution_start="1675035980758" data-outputid="619a4c17-883a-40e3-8062-f34bf569d78d" data-source_hash="1b13f66d" data-execution_count="64">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>sns.catplot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'weather'</span>, y <span class="op">=</span> <span class="st">'tavg'</span>, kind <span class="op">=</span> <span class="st">'box'</span>, col <span class="op">=</span> <span class="st">'season'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-65-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="create-a-new-attribute-current" class="level2">
<h2 class="anchored" data-anchor-id="create-a-new-attribute-current">Create a new attribute, current</h2>
<div class="cell" data-cell_id="a726d8be0ef147e6abfc8a3ad8ebcd36" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:361}" data-deepnote_cell_type="code" data-execution_millis="41" data-execution_start="1675035981677" data-outputid="5c5bd5f9-fdf6-407d-81c8-d3903d02100d" data-source_hash="4b1a3d45" data-execution_count="65">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'current'</span>] <span class="op">=</span> np.select([df[<span class="st">'year'</span>] <span class="op">==</span> <span class="dv">2022</span>, df[<span class="st">'year'</span>] <span class="op">!=</span> <span class="dv">2022</span>],[<span class="st">'current'</span>, <span class="st">'past'</span>])</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>df.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
Int64Index: 46020 entries, 0 to 45989
Data columns (total 28 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   date            46020 non-null  datetime64[ns]
 1   year            46020 non-null  int64         
 2   month           46020 non-null  int64         
 3   day             46020 non-null  int64         
 4   high            46020 non-null  float64       
 5   low             46020 non-null  float64       
 6   precip          46020 non-null  float64       
 7   snow            46020 non-null  float64       
 8   snowcover       46020 non-null  float64       
 9   high_max        46020 non-null  float64       
 10  low_max         46020 non-null  float64       
 11  precip_max      46020 non-null  float64       
 12  snow_max        46020 non-null  float64       
 13  snowcover_max   46020 non-null  float64       
 14  high_min        46020 non-null  float64       
 15  low_min         46020 non-null  float64       
 16  precip_min      46020 non-null  float64       
 17  snow_min        46020 non-null  float64       
 18  snowcover_min   46020 non-null  float64       
 19  high_mean       46020 non-null  float64       
 20  low_mean        46020 non-null  float64       
 21  precip_mean     46020 non-null  float64       
 22  snow_mean       46020 non-null  float64       
 23  snowcover_mean  46020 non-null  float64       
 24  tavg            46020 non-null  float64       
 25  weather         46020 non-null  object        
 26  season          46020 non-null  object        
 27  current         46020 non-null  object        
dtypes: datetime64[ns](1), float64(21), int64(3), object(3)
memory usage: 11.2+ MB</code></pre>
</div>
</div>
<div class="cell" data-cell_id="0a416d061ebd4e89b72bd0869bde4ff5" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:367}" data-deepnote_cell_type="code" data-execution_millis="2782" data-execution_start="1675035981720" data-outputid="3f137106-2c0b-4d94-f20d-b18cff46ac22" data-source_hash="38ae200c" data-execution_count="66">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>sns.relplot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'high'</span>, y <span class="op">=</span> <span class="st">'low'</span>, hue <span class="op">=</span> <span class="st">'current'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-67-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="f20ed79144e04f29b235589d777db690" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:373}" data-deepnote_cell_type="code" data-execution_millis="2753" data-execution_start="1675035984503" data-outputid="c6e1d819-b83b-4188-c272-523d87b112b4" data-source_hash="b6d88b7b" data-execution_count="67">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>sns.relplot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'snow'</span>, y <span class="op">=</span> <span class="st">'snowcover'</span>, hue <span class="op">=</span> <span class="st">'current'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-68-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="7a69e5778a3641b2813f361e7602c898" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:379}" data-deepnote_cell_type="code" data-execution_millis="2844" data-execution_start="1675035987254" data-outputid="b7fa95ce-f7a2-494e-e6dd-31502de42331" data-source_hash="b9a54548" data-execution_count="68">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>sns.relplot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'tavg'</span>, y <span class="op">=</span> <span class="st">'precip'</span>, hue <span class="op">=</span> <span class="st">'current'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-69-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="58f2f9c29c1349ddad3f0d9a6488ae87" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:385}" data-deepnote_cell_type="code" data-execution_millis="3668" data-execution_start="1675035990095" data-outputid="29dac6e5-207c-4fcb-9fba-5b489e34fabf" data-source_hash="cd9b7272" data-execution_count="69">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>sns.relplot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'tavg'</span>, y <span class="op">=</span> <span class="st">'precip'</span>, hue <span class="op">=</span> <span class="st">'current'</span>, col <span class="op">=</span> <span class="st">'season'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-70-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-cell_id="845f63e6f6aa48aca73706c856d82583" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:391}" data-deepnote_cell_type="code" data-execution_millis="90" data-execution_start="1675035993769" data-outputid="ab911713-bb30-4be8-933d-bef97294afa7" data-source_hash="2acd0b04" data-execution_count="70">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>df.loc[(df[<span class="st">'current'</span>] <span class="op">==</span> <span class="st">'current'</span>) <span class="op">&amp;</span> (df[<span class="st">'season'</span>] <span class="op">==</span> <span class="st">'summer'</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="70">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">date</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">month</th>
<th data-quarto-table-cell-role="th">day</th>
<th data-quarto-table-cell-role="th">high</th>
<th data-quarto-table-cell-role="th">low</th>
<th data-quarto-table-cell-role="th">precip</th>
<th data-quarto-table-cell-role="th">snow</th>
<th data-quarto-table-cell-role="th">snowcover</th>
<th data-quarto-table-cell-role="th">high_max</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">snowcover_min</th>
<th data-quarto-table-cell-role="th">high_mean</th>
<th data-quarto-table-cell-role="th">low_mean</th>
<th data-quarto-table-cell-role="th">precip_mean</th>
<th data-quarto-table-cell-role="th">snow_mean</th>
<th data-quarto-table-cell-role="th">snowcover_mean</th>
<th data-quarto-table-cell-role="th">tavg</th>
<th data-quarto-table-cell-role="th">weather</th>
<th data-quarto-table-cell-role="th">season</th>
<th data-quarto-table-cell-role="th">current</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">19151</td>
<td>2022-06-01</td>
<td>2022</td>
<td>6</td>
<td>1</td>
<td>54.0</td>
<td>39.0</td>
<td>0.580000</td>
<td>0.0</td>
<td>0.0</td>
<td>89.0</td>
<td>...</td>
<td>0.0</td>
<td>73.806452</td>
<td>48.096774</td>
<td>0.118348</td>
<td>0.000000</td>
<td>0.0</td>
<td>46.5</td>
<td>rain</td>
<td>summer</td>
<td>current</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">19277</td>
<td>2022-06-02</td>
<td>2022</td>
<td>6</td>
<td>2</td>
<td>69.0</td>
<td>39.0</td>
<td>0.000000</td>
<td>0.0</td>
<td>0.0</td>
<td>92.0</td>
<td>...</td>
<td>0.0</td>
<td>75.588710</td>
<td>48.274194</td>
<td>0.062946</td>
<td>0.021127</td>
<td>0.0</td>
<td>54.0</td>
<td>sunny</td>
<td>summer</td>
<td>current</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">19403</td>
<td>2022-06-03</td>
<td>2022</td>
<td>6</td>
<td>3</td>
<td>73.0</td>
<td>45.0</td>
<td>0.060000</td>
<td>0.0</td>
<td>0.0</td>
<td>95.0</td>
<td>...</td>
<td>0.0</td>
<td>75.419355</td>
<td>48.870968</td>
<td>0.090370</td>
<td>0.009859</td>
<td>0.0</td>
<td>59.0</td>
<td>rain</td>
<td>summer</td>
<td>current</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">19529</td>
<td>2022-06-04</td>
<td>2022</td>
<td>6</td>
<td>4</td>
<td>83.0</td>
<td>44.0</td>
<td>0.000000</td>
<td>0.0</td>
<td>0.0</td>
<td>94.0</td>
<td>...</td>
<td>0.0</td>
<td>76.129032</td>
<td>49.193548</td>
<td>0.125727</td>
<td>0.000000</td>
<td>0.0</td>
<td>63.5</td>
<td>sunny</td>
<td>summer</td>
<td>current</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">19655</td>
<td>2022-06-05</td>
<td>2022</td>
<td>6</td>
<td>5</td>
<td>80.0</td>
<td>52.0</td>
<td>0.093125</td>
<td>0.0</td>
<td>0.0</td>
<td>95.0</td>
<td>...</td>
<td>0.0</td>
<td>76.790323</td>
<td>49.822581</td>
<td>0.093125</td>
<td>0.000000</td>
<td>0.0</td>
<td>66.0</td>
<td>rain</td>
<td>summer</td>
<td>current</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">30113</td>
<td>2022-08-27</td>
<td>2022</td>
<td>8</td>
<td>27</td>
<td>91.0</td>
<td>56.0</td>
<td>0.000000</td>
<td>0.0</td>
<td>0.0</td>
<td>96.0</td>
<td>...</td>
<td>0.0</td>
<td>84.032520</td>
<td>56.886179</td>
<td>0.031028</td>
<td>0.000000</td>
<td>0.0</td>
<td>73.5</td>
<td>sunny</td>
<td>summer</td>
<td>current</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">30239</td>
<td>2022-08-28</td>
<td>2022</td>
<td>8</td>
<td>28</td>
<td>94.0</td>
<td>69.0</td>
<td>0.000000</td>
<td>0.0</td>
<td>0.0</td>
<td>96.0</td>
<td>...</td>
<td>0.0</td>
<td>83.910569</td>
<td>56.341463</td>
<td>0.035688</td>
<td>0.000000</td>
<td>0.0</td>
<td>81.5</td>
<td>sunny</td>
<td>summer</td>
<td>current</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">30365</td>
<td>2022-08-29</td>
<td>2022</td>
<td>8</td>
<td>29</td>
<td>86.0</td>
<td>53.0</td>
<td>0.000000</td>
<td>0.0</td>
<td>0.0</td>
<td>97.0</td>
<td>...</td>
<td>0.0</td>
<td>83.601626</td>
<td>56.048780</td>
<td>0.036903</td>
<td>0.000000</td>
<td>0.0</td>
<td>69.5</td>
<td>sunny</td>
<td>summer</td>
<td>current</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">30491</td>
<td>2022-08-30</td>
<td>2022</td>
<td>8</td>
<td>30</td>
<td>91.0</td>
<td>54.0</td>
<td>0.000000</td>
<td>0.0</td>
<td>0.0</td>
<td>96.0</td>
<td>...</td>
<td>0.0</td>
<td>83.536585</td>
<td>55.780488</td>
<td>0.060000</td>
<td>0.000000</td>
<td>0.0</td>
<td>72.5</td>
<td>sunny</td>
<td>summer</td>
<td>current</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">30617</td>
<td>2022-08-31</td>
<td>2022</td>
<td>8</td>
<td>31</td>
<td>90.0</td>
<td>57.0</td>
<td>0.010000</td>
<td>0.0</td>
<td>0.0</td>
<td>96.0</td>
<td>...</td>
<td>0.0</td>
<td>83.483607</td>
<td>54.860656</td>
<td>0.081226</td>
<td>0.000000</td>
<td>0.0</td>
<td>73.5</td>
<td>rain</td>
<td>summer</td>
<td>current</td>
</tr>
</tbody>
</table>

<p>92 rows × 28 columns</p>
</div>
</div>
</div>
<div class="cell" data-cell_id="abcaeb9c43ad4e9ab94c28e6dbacf292" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:397}" data-deepnote_cell_type="code" data-execution_millis="3690" data-execution_start="1675035993902" data-outputid="1bde9bfb-1997-4d31-f534-aa27af644732" data-source_hash="5a189378" data-execution_count="71">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>sns.relplot(data <span class="op">=</span> df, x <span class="op">=</span> <span class="st">'low'</span>, y <span class="op">=</span> <span class="st">'high'</span>, hue <span class="op">=</span> <span class="st">'current'</span>, col <span class="op">=</span> <span class="st">'season'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="BoulderClimateCaseStudy_files/figure-html/cell-72-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="normalization" class="level2">
<h2 class="anchored" data-anchor-id="normalization">Normalization</h2>
<div class="cell" data-cell_id="7817d056862a42c580a22c656e5506e4" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:409}" data-deepnote_cell_type="code" data-execution_millis="3083900" data-execution_start="1675035997610" data-source_hash="4c296541" data-execution_count="72">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'tavg_normal'</span>] <span class="op">=</span> (df[<span class="st">'tavg'</span>] <span class="op">-</span> df[<span class="st">'tavg'</span>].<span class="bu">min</span>())<span class="op">/</span>df[<span class="st">'tavg'</span>].<span class="bu">max</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-cell_id="3a664d7316024d0984cddf68ea29812d" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:415}" data-deepnote_cell_type="code" data-execution_millis="3083900" data-execution_start="1675035997611" data-source_hash="4d6605f7" data-execution_count="73">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'precip_normal'</span>] <span class="op">=</span> (df[<span class="st">'precip'</span>] <span class="op">-</span> df[<span class="st">'precip'</span>].<span class="bu">min</span>())<span class="op">/</span>df[<span class="st">'precip'</span>].<span class="bu">max</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-cell_id="f2d0e76f65a14ca89aa3a48b698b461b" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:421}" data-deepnote_cell_type="code" data-execution_millis="3083869" data-execution_start="1675035997611" data-source_hash="27833ea5" data-execution_count="74">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'snow_normal_zscore'</span>] <span class="op">=</span> (df[<span class="st">'snow'</span>] <span class="op">-</span> df[<span class="st">'snow'</span>].mean())<span class="op">/</span>df[<span class="st">'snow'</span>].var()   <span class="co"># might have to be std instead of var</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-cell_id="2c9d38c84cba4ee68442ba8004fdc602" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:427}" data-deepnote_cell_type="code" data-execution_millis="1" data-execution_start="1675035997612" data-source_hash="ae6d2c96" data-execution_count="75">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'snow_normal'</span>] <span class="op">=</span> (df[<span class="st">'snow'</span>] <span class="op">-</span> df[<span class="st">'snow'</span>].<span class="bu">min</span>())<span class="op">/</span>df[<span class="st">'snow'</span>].<span class="bu">max</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-cell_id="a6d53f63645049a79f65d241bfdd4a6d" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:523}" data-deepnote_cell_type="code" data-execution_millis="20" data-execution_start="1675035997615" data-source_hash="de1e323c" data-tags="[]" data-execution_count="76">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>df.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
Int64Index: 46020 entries, 0 to 45989
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype         
---  ------              --------------  -----         
 0   date                46020 non-null  datetime64[ns]
 1   year                46020 non-null  int64         
 2   month               46020 non-null  int64         
 3   day                 46020 non-null  int64         
 4   high                46020 non-null  float64       
 5   low                 46020 non-null  float64       
 6   precip              46020 non-null  float64       
 7   snow                46020 non-null  float64       
 8   snowcover           46020 non-null  float64       
 9   high_max            46020 non-null  float64       
 10  low_max             46020 non-null  float64       
 11  precip_max          46020 non-null  float64       
 12  snow_max            46020 non-null  float64       
 13  snowcover_max       46020 non-null  float64       
 14  high_min            46020 non-null  float64       
 15  low_min             46020 non-null  float64       
 16  precip_min          46020 non-null  float64       
 17  snow_min            46020 non-null  float64       
 18  snowcover_min       46020 non-null  float64       
 19  high_mean           46020 non-null  float64       
 20  low_mean            46020 non-null  float64       
 21  precip_mean         46020 non-null  float64       
 22  snow_mean           46020 non-null  float64       
 23  snowcover_mean      46020 non-null  float64       
 24  tavg                46020 non-null  float64       
 25  weather             46020 non-null  object        
 26  season              46020 non-null  object        
 27  current             46020 non-null  object        
 28  tavg_normal         46020 non-null  float64       
 29  precip_normal       46020 non-null  float64       
 30  snow_normal_zscore  46020 non-null  float64       
 31  snow_normal         46020 non-null  float64       
dtypes: datetime64[ns](1), float64(25), int64(3), object(3)
memory usage: 12.6+ MB</code></pre>
</div>
</div>
</section>
</section>
<section id="now-lets-save-the-dataset" class="level1">
<h1>Now let’s save the dataset</h1>
<div class="cell" data-cell_id="310fd36387f74687884fe52c9bc73268" data-deepnote_app_coordinates="{&quot;h&quot;:5,&quot;w&quot;:12,&quot;x&quot;:0,&quot;y&quot;:439}" data-deepnote_cell_type="code" data-execution_millis="1068" data-execution_start="1675035997634" data-outputid="ee33805f-a56d-4f16-b52a-18ac17748b38" data-source_hash="f27df8f6" data-execution_count="77">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>df.to_csv(<span class="st">"BoulderClimatePreProcessed.csv"</span>, index<span class="op">=</span> <span class="va">False</span>)</span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>df2 <span class="op">=</span>pd.read_csv(<span class="st">"BoulderClimatePreProcessed.csv"</span>)</span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a>df2.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="77">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">date</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">month</th>
<th data-quarto-table-cell-role="th">day</th>
<th data-quarto-table-cell-role="th">high</th>
<th data-quarto-table-cell-role="th">low</th>
<th data-quarto-table-cell-role="th">precip</th>
<th data-quarto-table-cell-role="th">snow</th>
<th data-quarto-table-cell-role="th">snowcover</th>
<th data-quarto-table-cell-role="th">high_max</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">snow_mean</th>
<th data-quarto-table-cell-role="th">snowcover_mean</th>
<th data-quarto-table-cell-role="th">tavg</th>
<th data-quarto-table-cell-role="th">weather</th>
<th data-quarto-table-cell-role="th">season</th>
<th data-quarto-table-cell-role="th">current</th>
<th data-quarto-table-cell-role="th">tavg_normal</th>
<th data-quarto-table-cell-role="th">precip_normal</th>
<th data-quarto-table-cell-role="th">snow_normal_zscore</th>
<th data-quarto-table-cell-role="th">snow_normal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1897-01-01</td>
<td>1897</td>
<td>1</td>
<td>1</td>
<td>41.243902</td>
<td>18.747967</td>
<td>0.025478</td>
<td>0.529851</td>
<td>2.152542</td>
<td>70.0</td>
<td>...</td>
<td>0.529851</td>
<td>2.152542</td>
<td>29.995935</td>
<td>snow</td>
<td>winter</td>
<td>past</td>
<td>0.499955</td>
<td>0.002806</td>
<td>0.344903</td>
<td>0.023975</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1897-01-02</td>
<td>1897</td>
<td>1</td>
<td>2</td>
<td>43.715447</td>
<td>17.861789</td>
<td>0.011441</td>
<td>0.294203</td>
<td>1.968254</td>
<td>70.0</td>
<td>...</td>
<td>0.294203</td>
<td>1.968254</td>
<td>30.788618</td>
<td>snow</td>
<td>winter</td>
<td>past</td>
<td>0.508762</td>
<td>0.001260</td>
<td>0.048053</td>
<td>0.013312</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1897-01-03</td>
<td>1897</td>
<td>1</td>
<td>3</td>
<td>43.780488</td>
<td>19.634146</td>
<td>0.025424</td>
<td>0.453623</td>
<td>2.351852</td>
<td>68.0</td>
<td>...</td>
<td>0.453623</td>
<td>2.351852</td>
<td>31.707317</td>
<td>snow</td>
<td>winter</td>
<td>past</td>
<td>0.518970</td>
<td>0.002800</td>
<td>0.248878</td>
<td>0.020526</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>1897-01-04</td>
<td>1897</td>
<td>1</td>
<td>4</td>
<td>43.943089</td>
<td>19.918699</td>
<td>0.028509</td>
<td>0.523077</td>
<td>2.322034</td>
<td>67.0</td>
<td>...</td>
<td>0.523077</td>
<td>2.322034</td>
<td>31.930894</td>
<td>snow</td>
<td>winter</td>
<td>past</td>
<td>0.521454</td>
<td>0.003140</td>
<td>0.336370</td>
<td>0.023669</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>1897-01-05</td>
<td>1897</td>
<td>1</td>
<td>5</td>
<td>44.691057</td>
<td>20.146341</td>
<td>0.026991</td>
<td>0.557812</td>
<td>2.410714</td>
<td>69.0</td>
<td>...</td>
<td>0.557812</td>
<td>2.410714</td>
<td>32.418699</td>
<td>snow</td>
<td>winter</td>
<td>past</td>
<td>0.526874</td>
<td>0.002973</td>
<td>0.380127</td>
<td>0.025240</td>
</tr>
</tbody>
</table>

<p>5 rows × 32 columns</p>
</div>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>