<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Analyze Your Runkeeper Fitness Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="FitnessData_files/libs/clipboard/clipboard.min.js"></script>
<script src="FitnessData_files/libs/quarto-html/quarto.js"></script>
<script src="FitnessData_files/libs/quarto-html/popper.min.js"></script>
<script src="FitnessData_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="FitnessData_files/libs/quarto-html/anchor.min.js"></script>
<link href="FitnessData_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="FitnessData_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="FitnessData_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="FitnessData_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="FitnessData_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#obtain-and-review-raw-data" id="toc-obtain-and-review-raw-data" class="nav-link active" data-scroll-target="#obtain-and-review-raw-data">1. Obtain and review raw data</a></li>
  <li><a href="#data-preprocessing" id="toc-data-preprocessing" class="nav-link" data-scroll-target="#data-preprocessing">2. Data preprocessing</a></li>
  <li><a href="#dealing-with-missing-values" id="toc-dealing-with-missing-values" class="nav-link" data-scroll-target="#dealing-with-missing-values">3. Dealing with missing values</a></li>
  <li><a href="#plot-running-data" id="toc-plot-running-data" class="nav-link" data-scroll-target="#plot-running-data">4. Plot running data</a></li>
  <li><a href="#running-statistics" id="toc-running-statistics" class="nav-link" data-scroll-target="#running-statistics">5. Running statistics</a></li>
  <li><a href="#visualization-with-averages" id="toc-visualization-with-averages" class="nav-link" data-scroll-target="#visualization-with-averages">6. Visualization with averages</a></li>
  <li><a href="#did-i-reach-my-goals" id="toc-did-i-reach-my-goals" class="nav-link" data-scroll-target="#did-i-reach-my-goals">7. Did I reach my goals?</a></li>
  <li><a href="#am-i-progressing" id="toc-am-i-progressing" class="nav-link" data-scroll-target="#am-i-progressing">8. Am I progressing?</a></li>
  <li><a href="#training-intensity" id="toc-training-intensity" class="nav-link" data-scroll-target="#training-intensity">9. Training intensity</a></li>
  <li><a href="#detailed-summary-report" id="toc-detailed-summary-report" class="nav-link" data-scroll-target="#detailed-summary-report">10. Detailed summary report</a></li>
  <li><a href="#fun-facts" id="toc-fun-facts" class="nav-link" data-scroll-target="#fun-facts">11. Fun facts</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analyze Your Runkeeper Fitness Data</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="obtain-and-review-raw-data" class="level2">
<h2 class="anchored" data-anchor-id="obtain-and-review-raw-data">1. Obtain and review raw data</h2>
<p>
One day, my old running friend and I were chatting about our running styles, training habits, and achievements, when I suddenly realized that I could take an in-depth analytical look at my training. I have been using a popular GPS fitness tracker called <a href="https://runkeeper.com/">Runkeeper</a> for years and decided it was time to analyze my running data to see how I was doing.
</p>
<p>
Since 2012, I’ve been using the Runkeeper app, and it’s great. One key feature: its excellent data export. Anyone who has a smartphone can download the app and analyze their data like we will in this notebook.
</p>
<p>
<img src="https://assets.datacamp.com/production/project_727/img/runner_in_blue.jpg" alt="Runner in blue" title="Explore world, explore your data!">
</p>
<p>
After logging your run, the first step is to export the data from Runkeeper (which I’ve done already). Then import the data and start exploring to find potential problems. After that, create data cleaning strategies to fix the issues. Finally, analyze and visualize the clean time-series data.
</p>
<p>
I exported seven years worth of my training data, from 2012 through 2018. The data is a CSV file where each row is a single training activity. Let’s load and inspect it.
</p>
<div class="cell" data-dc="{&quot;key&quot;:&quot;4&quot;}" data-tags="[&quot;sample_code&quot;]" data-execution_count="163">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import pandas</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Define file containing dataset</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>runkeeper_file <span class="op">=</span> <span class="st">'datasets/cardioActivities.csv'</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create DataFrame with parse_dates and index_col parameters </span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>df_activities <span class="op">=</span> pd.read_csv(runkeeper_file,parse_dates<span class="op">=</span><span class="va">True</span>,index_col<span class="op">=</span><span class="st">'Date'</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># First look at exported data: select sample of 3 random rows </span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>display(df_activities.sample(n<span class="op">=</span><span class="dv">3</span>))</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Print DataFrame summary</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>df_activities.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Activity Id</th>
      <th>Type</th>
      <th>Route Name</th>
      <th>Distance (km)</th>
      <th>Duration</th>
      <th>Average Pace</th>
      <th>Average Speed (km/h)</th>
      <th>Calories Burned</th>
      <th>Climb (m)</th>
      <th>Average Heart Rate (bpm)</th>
      <th>Friend's Tagged</th>
      <th>Notes</th>
      <th>GPX File</th>
    </tr>
    <tr>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>2016-02-15 18:37:04</th>
      <td>c41ee42c-c911-4367-8594-e86cffbec427</td>
      <td>Running</td>
      <td>NaN</td>
      <td>10.02</td>
      <td>1:00:08</td>
      <td>6:00</td>
      <td>10.00</td>
      <td>703.0</td>
      <td>92</td>
      <td>157.0</td>
      <td>NaN</td>
      <td>TomTom MySports Watch</td>
      <td>2016-02-15-183704.gpx</td>
    </tr>
    <tr>
      <th>2017-07-19 18:50:31</th>
      <td>ebe894be-7567-4b56-91ab-164554e20357</td>
      <td>Running</td>
      <td>NaN</td>
      <td>12.80</td>
      <td>1:08:04</td>
      <td>5:19</td>
      <td>11.28</td>
      <td>891.0</td>
      <td>170</td>
      <td>143.0</td>
      <td>NaN</td>
      <td>TomTom MySports Watch</td>
      <td>2017-07-19-185031.gpx</td>
    </tr>
    <tr>
      <th>2014-09-15 18:30:00</th>
      <td>a2306eac-c313-4abd-a653-e62bb74f9e3b</td>
      <td>Running</td>
      <td>NaN</td>
      <td>9.55</td>
      <td>48:54</td>
      <td>5:07</td>
      <td>11.72</td>
      <td>684.0</td>
      <td>51</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>2014-09-15-183000.gpx</td>
    </tr>
  </tbody>
</table>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
DatetimeIndex: 508 entries, 2018-11-11 14:05:12 to 2012-08-22 18:53:54
Data columns (total 13 columns):
Activity Id                 508 non-null object
Type                        508 non-null object
Route Name                  1 non-null object
Distance (km)               508 non-null float64
Duration                    508 non-null object
Average Pace                508 non-null object
Average Speed (km/h)        508 non-null float64
Calories Burned             508 non-null float64
Climb (m)                   508 non-null int64
Average Heart Rate (bpm)    294 non-null float64
Friend's Tagged             0 non-null float64
Notes                       231 non-null object
GPX File                    504 non-null object
dtypes: float64(5), int64(1), object(7)
memory usage: 55.6+ KB</code></pre>
</div>
</div>
</section>
<section id="data-preprocessing" class="level2">
<h2 class="anchored" data-anchor-id="data-preprocessing">2. Data preprocessing</h2>
<p>
Lucky for us, the column names Runkeeper provides are informative, and we don’t need to rename any columns.
</p>
<p>
But, we do notice missing values using the <code>info()</code> method. What are the reasons for these missing values? It depends. Some heart rate information is missing because I didn’t always use a cardio sensor. In the case of the <code>Notes</code> column, it is an optional field that I sometimes left blank. Also, I only used the <code>Route Name</code> column once, and never used the <code>Friend’s Tagged</code> column.
</p>
<p>
We’ll fill in missing values in the heart rate column to avoid misleading results later, but right now, our first data preprocessing steps will be to:
</p>
<ul>
<li>
Remove columns not useful for our analysis.
</li>
<li>
Replace the “Other” activity type to “Unicycling” because that was always the “Other” activity.
</li>
<li>
Count missing values.
</li>
</ul>
<div class="cell" data-dc="{&quot;key&quot;:&quot;12&quot;}" data-tags="[&quot;sample_code&quot;]" data-execution_count="165">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define list of columns to be deleted</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>cols_to_drop <span class="op">=</span> [<span class="st">'Friend</span><span class="ch">\'</span><span class="st">s Tagged'</span>,<span class="st">'Route Name'</span>,<span class="st">'GPX File'</span>,<span class="st">'Activity Id'</span>,<span class="st">'Calories Burned'</span>, <span class="st">'Notes'</span>]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Delete unnecessary columns</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>df_activities.drop(columns<span class="op">=</span>cols_to_drop,inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Count types of training activities</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>display(df_activities.Type.value_counts())</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename 'Other' type to 'Unicycling'</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>df_activities[<span class="st">'Type'</span>] <span class="op">=</span> df_activities[<span class="st">'Type'</span>].replace(<span class="st">'Other'</span>,<span class="st">'Unicycling'</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Count missing values for each column</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>df_activities.isnull().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>Running    459
Cycling     29
Walking     18
Other        2
Name: Type, dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="165">
<pre><code>Type                          0
Distance (km)                 0
Duration                      0
Average Pace                  0
Average Speed (km/h)          0
Climb (m)                     0
Average Heart Rate (bpm)    214
dtype: int64</code></pre>
</div>
</div>
</section>
<section id="dealing-with-missing-values" class="level2">
<h2 class="anchored" data-anchor-id="dealing-with-missing-values">3. Dealing with missing values</h2>
<p>
As we can see from the last output, there are 214 missing entries for my average heart rate.
</p>
<p>
We can’t go back in time to get those data, but we can fill in the missing values with an average value. This process is called <em>mean imputation</em>. When imputing the mean to fill in missing data, we need to consider that the average heart rate varies for different activities (e.g., walking vs.&nbsp;running). We’ll filter the DataFrames by activity type (<code>Type</code>) and calculate each activity’s mean heart rate, then fill in the missing values with those means.
</p>
<div class="cell" data-dc="{&quot;key&quot;:&quot;19&quot;}" data-tags="[&quot;sample_code&quot;]" data-execution_count="167">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate sample means for heart rate for each training activity type </span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>avg_hr_run <span class="op">=</span> df_activities[df_activities[<span class="st">'Type'</span>] <span class="op">==</span> <span class="st">'Running'</span>][<span class="st">'Average Heart Rate (bpm)'</span>].mean()</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>avg_hr_cycle <span class="op">=</span> df_activities[df_activities[<span class="st">'Type'</span>] <span class="op">==</span> <span class="st">'Cycling'</span>][<span class="st">'Average Heart Rate (bpm)'</span>].mean()</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Split whole DataFrame into several, specific for different activities</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>df_run <span class="op">=</span> df_activities[df_activities[<span class="st">'Type'</span>] <span class="op">==</span> <span class="st">'Running'</span>].copy()</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>df_walk <span class="op">=</span> df_activities[df_activities[<span class="st">'Type'</span>] <span class="op">==</span> <span class="st">'Walking'</span>].copy()</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>df_cycle <span class="op">=</span> df_activities[df_activities[<span class="st">'Type'</span>] <span class="op">==</span> <span class="st">'Cycling'</span>].copy()</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Filling missing values with counted means  </span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>df_walk[<span class="st">'Average Heart Rate (bpm)'</span>].fillna(<span class="dv">110</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>df_run[<span class="st">'Average Heart Rate (bpm)'</span>].fillna(<span class="bu">int</span>(avg_hr_run), inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>df_cycle[<span class="st">'Average Heart Rate (bpm)'</span>].fillna(<span class="bu">int</span>(avg_hr_cycle), inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Count missing values for each column in running data</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>df_run.isnull().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="167">
<pre><code>Type                        0
Distance (km)               0
Duration                    0
Average Pace                0
Average Speed (km/h)        0
Climb (m)                   0
Average Heart Rate (bpm)    0
dtype: int64</code></pre>
</div>
</div>
</section>
<section id="plot-running-data" class="level2">
<h2 class="anchored" data-anchor-id="plot-running-data">4. Plot running data</h2>
<p>
Now we can create our first plot! As we found earlier, most of the activities in my data were running (459 of them to be exact). There are only 29, 18, and two instances for cycling, walking, and unicycling, respectively. So for now, let’s focus on plotting the different running metrics.
</p>
<p>
An excellent first visualization is a figure with four subplots, one for each running metric (each numerical column). Each subplot will have a different y-axis, which is explained in each legend. The x-axis, <code>Date</code>, is shared among all subplots.
</p>
<div class="cell" data-dc="{&quot;key&quot;:&quot;26&quot;}" data-tags="[&quot;sample_code&quot;]" data-execution_count="169">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>matplotlib inline</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Import matplotlib, set style and ignore warning</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>matplotlib inline</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>plt.style.use(<span class="st">'ggplot'</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    action<span class="op">=</span><span class="st">'ignore'</span>, module<span class="op">=</span><span class="st">'matplotlib.figure'</span>, category<span class="op">=</span><span class="pp">UserWarning</span>,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    message<span class="op">=</span>(<span class="st">'This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.'</span>)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare data subsetting period from 2013 till 2018</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>runs_subset_2013_2018 <span class="op">=</span> df_run[<span class="st">'2019-01-01'</span>:<span class="st">'2013-01-01'</span>]</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Create, plot and customize in one step</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>runs_subset_2013_2018.plot(subplots<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>                           sharex<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>                           figsize<span class="op">=</span>(<span class="dv">12</span>,<span class="dv">16</span>),</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>                           linestyle<span class="op">=</span><span class="st">'none'</span>,</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>                           marker<span class="op">=</span><span class="st">'o'</span>,</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>                           markersize<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>                          )</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Show plot</span></span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="FitnessData_files/figure-html/cell-5-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="running-statistics" class="level2">
<h2 class="anchored" data-anchor-id="running-statistics">5. Running statistics</h2>
<p>
No doubt, running helps people stay mentally and physically healthy and productive at any age. And it is great fun! When runners talk to each other about their hobby, we not only discuss our results, but we also discuss different training strategies.
</p>
<p>
You’ll know you’re with a group of runners if you commonly hear questions like:
</p>
<ul>
<li>
What is your average distance?
</li>
<li>
How fast do you run?
</li>
<li>
Do you measure your heart rate?
</li>
<li>
How often do you train?
</li>
</ul>
<p>
Let’s find the answers to these questions in my data. If you look back at plots in Task 4, you can see the answer to, <em>Do you measure your heart rate?</em> Before 2015: no. To look at the averages, let’s only use the data from 2015 through 2018.
</p>
<p>
In pandas, the <code>resample()</code> method is similar to the <code>groupby()</code> method - with <code>resample()</code> you group by a specific time span. We’ll use <code>resample()</code> to group the time series data by a sampling period and apply several methods to each sampling period. In our case, we’ll resample annually and weekly.
</p>
<div class="cell" data-dc="{&quot;key&quot;:&quot;33&quot;}" data-tags="[&quot;sample_code&quot;]" data-execution_count="171">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare running data for the last 4 years</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>runs_subset_2015_2018 <span class="op">=</span> df_run[<span class="st">'2019-01-01'</span>:<span class="st">'2015-01-01'</span>]</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate annual statistics</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'How my average run looks in last 4 years:'</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>display(runs_subset_2015_2018.resample(<span class="st">'A'</span>).mean())</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate weekly statistics</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Weekly averages of last 4 years:'</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>display(runs_subset_2015_2018.resample(<span class="st">'W'</span>).mean().mean())</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean weekly counts</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>weekly_counts_average <span class="op">=</span> runs_subset_2015_2018[<span class="st">'Distance (km)'</span>].resample(<span class="st">'W'</span>).count().mean()</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'How many trainings per week I had on average:'</span>, weekly_counts_average)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>How my average run looks in last 4 years:</code></pre>
</div>
<div class="cell-output cell-output-display">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Distance (km)</th>
      <th>Average Speed (km/h)</th>
      <th>Climb (m)</th>
      <th>Average Heart Rate (bpm)</th>
    </tr>
    <tr>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>2015-12-31</th>
      <td>13.602805</td>
      <td>10.998902</td>
      <td>160.170732</td>
      <td>143.353659</td>
    </tr>
    <tr>
      <th>2016-12-31</th>
      <td>11.411667</td>
      <td>10.837778</td>
      <td>133.194444</td>
      <td>143.388889</td>
    </tr>
    <tr>
      <th>2017-12-31</th>
      <td>12.935176</td>
      <td>10.959059</td>
      <td>169.376471</td>
      <td>145.247059</td>
    </tr>
    <tr>
      <th>2018-12-31</th>
      <td>13.339063</td>
      <td>10.777969</td>
      <td>191.218750</td>
      <td>148.125000</td>
    </tr>
  </tbody>
</table>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Weekly averages of last 4 years:</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>Distance (km)                12.518176
Average Speed (km/h)         10.835473
Climb (m)                   158.325444
Average Heart Rate (bpm)    144.801775
dtype: float64</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>How many trainings per week I had on average: 1.5</code></pre>
</div>
</div>
</section>
<section id="visualization-with-averages" class="level2">
<h2 class="anchored" data-anchor-id="visualization-with-averages">6. Visualization with averages</h2>
<p>
Let’s plot the long term averages of my distance run and my heart rate with their raw data to visually compare the averages to each training session. Again, we’ll use the data from 2015 through 2018.
</p>
<p>
In this task, we will use <code>matplotlib</code> functionality for plot creation and customization.
</p>
<div class="cell" data-dc="{&quot;key&quot;:&quot;40&quot;}" data-tags="[&quot;sample_code&quot;]" data-execution_count="173">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare data</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>runs_subset_2015_2018 <span class="op">=</span> df_run[<span class="st">'2018'</span>:<span class="st">'2015'</span>]</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>runs_distance <span class="op">=</span> runs_subset_2015_2018[<span class="st">'Distance (km)'</span>]</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>runs_hr <span class="op">=</span> runs_subset_2015_2018[<span class="st">'Average Heart Rate (bpm)'</span>]</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create plot</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2) <span class="op">=</span> plt.subplots(<span class="dv">2</span>,sharex<span class="op">=</span><span class="va">True</span>,figsize<span class="op">=</span>(<span class="dv">12</span>,<span class="dv">8</span>))</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot and customize first subplot</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>runs_distance.plot(ax<span class="op">=</span>ax1)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>ax1.<span class="bu">set</span>(ylabel<span class="op">=</span><span class="st">'Distance (km)'</span>, title<span class="op">=</span><span class="st">'Historical data with averages'</span>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>ax1.axhline(runs_distance.mean(), color<span class="op">=</span><span class="st">'blue'</span>, linewidth<span class="op">=</span><span class="dv">1</span>, linestyle<span class="op">=</span><span class="st">'-.'</span>)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot and customize second subplot</span></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>runs_hr.plot(ax<span class="op">=</span>ax2, color<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>ax2.<span class="bu">set</span>(xlabel<span class="op">=</span><span class="st">'Date'</span>, ylabel<span class="op">=</span><span class="st">'Average Heart Rate (bpm)'</span>)</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>ax2.axhline(runs_hr.mean(),color<span class="op">=</span><span class="st">'blue'</span>,linewidth<span class="op">=</span><span class="dv">1</span>,linestyle<span class="op">=</span><span class="st">'-.'</span>)</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Show plot</span></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="FitnessData_files/figure-html/cell-7-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="did-i-reach-my-goals" class="level2">
<h2 class="anchored" data-anchor-id="did-i-reach-my-goals">7. Did I reach my goals?</h2>
<p>
To motivate myself to run regularly, I set a target goal of running 1000 km per year. Let’s visualize my annual running distance (km) from 2013 through 2018 to see if I reached my goal each year. Only stars in the green region indicate success.
</p>
<div class="cell" data-dc="{&quot;key&quot;:&quot;47&quot;}" data-tags="[&quot;sample_code&quot;]" data-execution_count="175">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare data</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>df_run_dist_annual <span class="op">=</span> df_run[<span class="st">'2018'</span>:<span class="st">'2013'</span>][<span class="st">'Distance (km)'</span>].resample(<span class="st">'A'</span>).<span class="bu">sum</span>()</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create plot</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>,<span class="dv">5</span>))</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot and customize</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> df_run_dist_annual.plot(marker<span class="op">=</span><span class="st">'*'</span>, markersize<span class="op">=</span><span class="dv">14</span>, linewidth<span class="op">=</span><span class="dv">0</span>, color<span class="op">=</span><span class="st">'blue'</span>)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>ax.<span class="bu">set</span>(ylim<span class="op">=</span>[<span class="dv">0</span>, <span class="dv">1210</span>], </span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>       xlim<span class="op">=</span>[<span class="st">'2012'</span>,<span class="st">'2019'</span>],</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>       ylabel<span class="op">=</span><span class="st">'Distance (km)'</span>,</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>       xlabel<span class="op">=</span><span class="st">'Years'</span>,</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>       title<span class="op">=</span><span class="st">'Annual totals for distance'</span>)</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>ax.axhspan(<span class="dv">1000</span>, <span class="dv">1210</span>, color<span class="op">=</span><span class="st">'green'</span>, alpha<span class="op">=</span><span class="fl">0.4</span>)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>ax.axhspan(<span class="dv">800</span>, <span class="dv">1000</span>, color<span class="op">=</span><span class="st">'yellow'</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>ax.axhspan(<span class="dv">0</span>,<span class="dv">800</span>, color<span class="op">=</span><span class="st">'red'</span>, alpha<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Show plot</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="FitnessData_files/figure-html/cell-8-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="am-i-progressing" class="level2">
<h2 class="anchored" data-anchor-id="am-i-progressing">8. Am I progressing?</h2>
<p>
Let’s dive a little deeper into the data to answer a tricky question: am I progressing in terms of my running skills?
</p>
<p>
To answer this question, we’ll decompose my weekly distance run and visually compare it to the raw data. A red trend line will represent the weekly distance run.
</p>
<p>
We are going to use <code>statsmodels</code> library to decompose the weekly trend.
</p>
<div class="cell" data-dc="{&quot;key&quot;:&quot;54&quot;}" data-tags="[&quot;sample_code&quot;]" data-execution_count="177">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import required library</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare data</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>df_run_dist_wkly <span class="op">=</span> df_run[<span class="st">'2018'</span>:<span class="st">'2013'</span>][<span class="st">'Distance (km)'</span>].resample(<span class="st">'W'</span>).bfill()</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>decomposed <span class="op">=</span> sm.tsa.seasonal_decompose(df_run_dist_wkly, extrapolate_trend<span class="op">=</span><span class="dv">1</span>, freq<span class="op">=</span><span class="dv">52</span>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create plot</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>,<span class="dv">5</span>))</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot and customize</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> decomposed.trend.plot(label<span class="op">=</span><span class="st">'Trend'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> decomposed.observed.plot(label<span class="op">=</span><span class="st">'Observed'</span>, linewidth<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Running distance trend'</span>)</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Show plot</span></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="FitnessData_files/figure-html/cell-9-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="training-intensity" class="level2">
<h2 class="anchored" data-anchor-id="training-intensity">9. Training intensity</h2>
<p>
Heart rate is a popular metric used to measure training intensity. Depending on age and fitness level, heart rates are grouped into different zones that people can target depending on training goals. A target heart rate during moderate-intensity activities is about 50-70% of maximum heart rate, while during vigorous physical activity it’s about 70-85% of maximum.
</p>
<p>
We’ll create a distribution plot of my heart rate data by training intensity. It will be a visual presentation for the number of activities from predefined training zones.
</p>
<div class="cell" data-dc="{&quot;key&quot;:&quot;61&quot;}" data-tags="[&quot;sample_code&quot;]" data-execution_count="179">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare data</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>hr_zones <span class="op">=</span> [<span class="dv">100</span>, <span class="dv">125</span>, <span class="dv">133</span>, <span class="dv">142</span>, <span class="dv">151</span>, <span class="dv">173</span>]</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>zone_names <span class="op">=</span> [<span class="st">'Easy'</span>, <span class="st">'Moderate'</span>, <span class="st">'Hard'</span>, <span class="st">'Very hard'</span>, <span class="st">'Maximal'</span>]</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>zone_colors <span class="op">=</span> [<span class="st">'green'</span>, <span class="st">'yellow'</span>, <span class="st">'orange'</span>, <span class="st">'tomato'</span>, <span class="st">'red'</span>]</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>df_run_hr_all <span class="op">=</span> df_run[<span class="st">'2019'</span>:<span class="st">'2015-03'</span>][<span class="st">'Average Heart Rate (bpm)'</span>]</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create plot</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>,<span class="dv">5</span>))</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot and customize</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>n, bins, patches <span class="op">=</span> ax.hist(df_run_hr_all, bins<span class="op">=</span>hr_zones, alpha<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="bu">len</span>(patches)):</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>    patches[i].set_facecolor(zone_colors[i])</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>ax.<span class="bu">set</span>(title<span class="op">=</span><span class="st">'Distribution of HR'</span>, ylabel<span class="op">=</span><span class="st">'Number of runs'</span>)</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>ax.xaxis.<span class="bu">set</span>(ticks<span class="op">=</span>hr_zones)</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>ax.set_xticklabels(labels<span class="op">=</span>zone_names,rotation<span class="op">=-</span><span class="dv">30</span>,ha<span class="op">=</span><span class="st">'left'</span>)</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Show plot</span></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="FitnessData_files/figure-html/cell-10-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="detailed-summary-report" class="level2">
<h2 class="anchored" data-anchor-id="detailed-summary-report">10. Detailed summary report</h2>
<p>
With all this data cleaning, analysis, and visualization, let’s create detailed summary tables of my training.
</p>
<p>
To do this, we’ll create two tables. The first table will be a summary of the distance (km) and climb (m) variables for each training activity. The second table will list the summary statistics for the average speed (km/hr), climb (m), and distance (km) variables for each training activity.
</p>
<div class="cell" data-dc="{&quot;key&quot;:&quot;68&quot;}" data-tags="[&quot;sample_code&quot;]" data-execution_count="181">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Concatenating three DataFrames</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>df_run_walk_cycle <span class="op">=</span> df_run.append([df_walk,df_cycle]).sort_index(ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>dist_climb_cols, speed_col <span class="op">=</span> [<span class="st">'Distance (km)'</span>, <span class="st">'Climb (m)'</span>], [<span class="st">'Average Speed (km/h)'</span>]</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating total distance and climb in each type of activities</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>df_totals <span class="op">=</span> df_run_walk_cycle.groupby(<span class="st">'Type'</span>)[dist_climb_cols].<span class="bu">sum</span>()</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Totals for different training types:'</span>)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>display(df_totals)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating summary statistics for each type of activities </span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>df_summary <span class="op">=</span> df_run_walk_cycle.groupby(<span class="st">'Type'</span>)[dist_climb_cols <span class="op">+</span> speed_col].describe()</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine totals with summary</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> dist_climb_cols:</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>    df_summary[i, <span class="st">'total'</span>] <span class="op">=</span> df_totals[i]</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Summary statistics for different training types:'</span>)</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>df_summary.stack()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Totals for different training types:</code></pre>
</div>
<div class="cell-output cell-output-display">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Distance (km)</th>
      <th>Climb (m)</th>
    </tr>
    <tr>
      <th>Type</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Cycling</th>
      <td>680.58</td>
      <td>6976</td>
    </tr>
    <tr>
      <th>Running</th>
      <td>5224.50</td>
      <td>57278</td>
    </tr>
    <tr>
      <th>Walking</th>
      <td>33.45</td>
      <td>349</td>
    </tr>
  </tbody>
</table>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Summary statistics for different training types:</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="181">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th>Average Speed (km/h)</th>
      <th>Climb (m)</th>
      <th>Distance (km)</th>
    </tr>
    <tr>
      <th>Type</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="9" valign="top">Cycling</th>
      <th>25%</th>
      <td>16.980000</td>
      <td>139.000000</td>
      <td>15.530000</td>
    </tr>
    <tr>
      <th>50%</th>
      <td>19.500000</td>
      <td>199.000000</td>
      <td>20.300000</td>
    </tr>
    <tr>
      <th>75%</th>
      <td>21.490000</td>
      <td>318.000000</td>
      <td>29.400000</td>
    </tr>
    <tr>
      <th>count</th>
      <td>29.000000</td>
      <td>29.000000</td>
      <td>29.000000</td>
    </tr>
    <tr>
      <th>max</th>
      <td>24.330000</td>
      <td>553.000000</td>
      <td>49.180000</td>
    </tr>
    <tr>
      <th>mean</th>
      <td>19.125172</td>
      <td>240.551724</td>
      <td>23.468276</td>
    </tr>
    <tr>
      <th>min</th>
      <td>11.380000</td>
      <td>58.000000</td>
      <td>11.410000</td>
    </tr>
    <tr>
      <th>std</th>
      <td>3.257100</td>
      <td>128.960289</td>
      <td>9.451040</td>
    </tr>
    <tr>
      <th>total</th>
      <td>NaN</td>
      <td>6976.000000</td>
      <td>680.580000</td>
    </tr>
    <tr>
      <th rowspan="9" valign="top">Running</th>
      <th>25%</th>
      <td>10.495000</td>
      <td>54.000000</td>
      <td>7.415000</td>
    </tr>
    <tr>
      <th>50%</th>
      <td>10.980000</td>
      <td>91.000000</td>
      <td>10.810000</td>
    </tr>
    <tr>
      <th>75%</th>
      <td>11.520000</td>
      <td>171.000000</td>
      <td>13.190000</td>
    </tr>
    <tr>
      <th>count</th>
      <td>459.000000</td>
      <td>459.000000</td>
      <td>459.000000</td>
    </tr>
    <tr>
      <th>max</th>
      <td>20.720000</td>
      <td>982.000000</td>
      <td>38.320000</td>
    </tr>
    <tr>
      <th>mean</th>
      <td>11.056296</td>
      <td>124.788671</td>
      <td>11.382353</td>
    </tr>
    <tr>
      <th>min</th>
      <td>5.770000</td>
      <td>0.000000</td>
      <td>0.760000</td>
    </tr>
    <tr>
      <th>std</th>
      <td>0.953273</td>
      <td>103.382177</td>
      <td>4.937853</td>
    </tr>
    <tr>
      <th>total</th>
      <td>NaN</td>
      <td>57278.000000</td>
      <td>5224.500000</td>
    </tr>
    <tr>
      <th rowspan="9" valign="top">Walking</th>
      <th>25%</th>
      <td>5.555000</td>
      <td>7.000000</td>
      <td>1.385000</td>
    </tr>
    <tr>
      <th>50%</th>
      <td>5.970000</td>
      <td>10.000000</td>
      <td>1.485000</td>
    </tr>
    <tr>
      <th>75%</th>
      <td>6.512500</td>
      <td>15.500000</td>
      <td>1.787500</td>
    </tr>
    <tr>
      <th>count</th>
      <td>18.000000</td>
      <td>18.000000</td>
      <td>18.000000</td>
    </tr>
    <tr>
      <th>max</th>
      <td>6.910000</td>
      <td>112.000000</td>
      <td>4.290000</td>
    </tr>
    <tr>
      <th>mean</th>
      <td>5.549444</td>
      <td>19.388889</td>
      <td>1.858333</td>
    </tr>
    <tr>
      <th>min</th>
      <td>1.040000</td>
      <td>5.000000</td>
      <td>1.220000</td>
    </tr>
    <tr>
      <th>std</th>
      <td>1.459309</td>
      <td>27.110100</td>
      <td>0.880055</td>
    </tr>
    <tr>
      <th>total</th>
      <td>NaN</td>
      <td>349.000000</td>
      <td>33.450000</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
</section>
<section id="fun-facts" class="level2">
<h2 class="anchored" data-anchor-id="fun-facts">11. Fun facts</h2>
<p>
To wrap up, let’s pick some fun facts out of the summary tables and solve the last exercise.
</p>
<p>
These data (my running history) represent 6 years, 2 months and 21 days. And I remember how many running shoes I went through–7.
</p>
<pre><code>FUN FACTS
- Average distance: 11.38 km
- Longest distance: 38.32 km
- Highest climb: 982 m
- Total climb: 57,278 m
- Total number of km run: 5,224 km
- Total runs: 459
- Number of running shoes gone through: 7 pairs
</code></pre>
<p>
The story of Forrest Gump is well known–the man, who for no particular reason decided to go for a “little run.” His epic run duration was 3 years, 2 months and 14 days (1169 days). In the picture you can see Forrest’s route of 24,700 km.
</p>
<pre><code>FORREST RUN FACTS
- Average distance: 21.13 km
- Total number of km run: 24,700 km
- Total runs: 1169
- Number of running shoes gone through: ...
</code></pre>
<p>
Assuming Forest and I go through running shoes at the same rate, figure out how many pairs of shoes Forrest needed for his run.
</p>
<p>
<img src="https://assets.datacamp.com/production/project_727/img/Forrest_Gump_running_route.png" alt="Forrest's route" title="Little run of Forrest Gump">
</p>
<div class="cell" data-dc="{&quot;key&quot;:&quot;75&quot;}" data-tags="[&quot;sample_code&quot;]" data-execution_count="183">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Count average shoes per lifetime (as km per pair) using our fun facts</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>average_shoes_lifetime <span class="op">=</span> (<span class="dv">100</span><span class="op">/</span><span class="dv">6</span>)<span class="op">*</span><span class="dv">7</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Count number of shoes for Forrest's run distance</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>shoes_for_forrest_run <span class="op">=</span> <span class="bu">round</span>((<span class="dv">7</span><span class="op">/</span><span class="fl">11.38</span>)<span class="op">*</span><span class="fl">21.13</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Forrest Gump would need </span><span class="sc">{}</span><span class="st"> pairs of shoes!'</span>.<span class="bu">format</span>(shoes_for_forrest_run))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Forrest Gump would need 13 pairs of shoes!</code></pre>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>