project:
  type: website

website:
  title: "Jasmine Kobayashi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects.qmd
        text: Projects
  sidebar: 
    style: "docked" 
    search: true
    tools: 
      - icon: linkedin
        href: https://www.linkedin.com/in/jasminekobayashi/
      - icon: github
        href: https://github.com/Rokkaan5

    contents:
      - about.qmd
      - section: "Projects"
        href: projects.qmd
        contents:
          - ML-SoWGap.qmd

    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



