---
title: "CSCI 5501: Data Structures & Algorithms"
---

[Fall 2022] ***Data Structures & Algorithms*** with Professor Di Wu at [CU Boulder](../../CUB.qmd)

## Homeworks

1. (Written HW)
2. [Simulation of a Coin Flip](HW/JasmineKobayashiA02a.ipynb)
    - `random.randint()`
    - monte carlo practice
3. [Student classes](HW/JasmineKobayashiA03b.ipynb)
    - Python class objects
        - abstract classes
4. [Greedy and Binary search](HW/JasmineKobayashiA04.ipynb)
5. [Insertion, selection, and bubble sort](HW/JasmineKobayashiA05a.ipynb)
6. [Recursion, Dynamic Programming](HW/JasmineKobayashiA06.ipynb)
    - Merge and Quick sort
    - Fibonacci Series and Recursion
7. [Sorting Functions](HW/JasmineKobayashiA07.ipynb)
    - Insertion and Binary Insertion Sort
    - Merge Sort
    - Monte Carlo
8. Strings
    - [Part A](HW/JasmineKobayashiA08a.ipynb)
        - creation
        - concatenation
        - splitting
        - slicing
        - traverse
    - [Part B](HW/JasmineKobayashiA08b.ipynb)
        - Caesar encoding, decoding, and breaker
9. (there wasn't a notebook when I downloaded these files)
10. [Numpy and Pandas](HW/JasmineKobayashiA10.ipynb)
    - Arrays
    - Dataframes

## Group Projects

**Team 4**: Strings

[Team 4 Example code here](team-projects-codes/Strings_python.ipynb)

**Team 8** (Vamsi Gontu, Sanyuta Nair, and me): ***general intro to tree structures***

- General intro to trees
- Heap Trees
- Tree traversal (pre-order, in-order, post-order)

[Team 8 Example code here](team-projects-codes/Team8_Trees.ipynb)

**Team 9** (Siddarth Tayi, ...): ***binary (search) trees***

[Team 9 Example code here](team-projects-codes/Team_9_Implmentation_of_Tree_and_Tree_algorithms.ipynb)


(There were other team presentations on other data structures, but I didn't save them)